//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:29 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Autor: Francisco
//     Fecha: 6/19/2014 1:29:29 PM
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
  using System.Text.RegularExpressions;
  using System.Collections.Generic;
namespace OSIS.PEPPAM.BOM
{
	/// <summary>
	/// The collection to hold 'Congregaciones_Master' entities
	/// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MyWorkGenerators", "0.0.0.00000")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey},Congregacion_Nombre={Congregacion_Nombre}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.NameTypeConverter))]
	public partial class Congregaciones_Master :  System.ICloneable, System.IComparable, System.IComparable<OSIS.PEPPAM.BOM.Congregaciones_Master>, CodeFluent.Runtime.ICodeFluentEntity, System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable<OSIS.PEPPAM.BOM.Congregaciones_Master>

	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'Congregaciones_Master' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'Circuito_Numero' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Circuito_Numero' property")]
			Circuito_Numero,
			/// <summary>
			/// Field mapping for the 'Congregacion_Direccion' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Congregacion_Direccion' property")]
			Congregacion_Direccion,
			/// <summary>
			/// Field mapping for the 'Congregacion_Nombre' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Congregacion_Nombre' property")]
			Congregacion_Nombre,
			/// <summary>
			/// Field mapping for the 'Congregacion_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Congregacion_Secuencia' property")]
			Congregacion_Secuencia,
			/// <summary>
			/// Field mapping for the 'Registro_Estado' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Estado' property")]
			Registro_Estado,
			/// <summary>
			/// Field mapping for the 'Registro_Fecha' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Fecha' property")]
			Registro_Fecha,
			/// <summary>
			/// Field mapping for the 'Registro_Usuario' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Usuario' property")]
			Registro_Usuario,
			/// <summary>
			/// Field mapping for the 'Zona_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Zona_Secuencia' property")]
			Zona_Secuencia,
		}
		#endregion

        private bool _raisePropertyChangedEvents = true;
        
        private CodeFluent.Runtime.CodeFluentEntityState _entityState;
        
		#region Property Holders

		/// <summary />
		protected int _circuito_Numero = -1;
		/// <summary />
		protected string _congregacion_Direccion = string.Empty;
		/// <summary />
		protected string _congregacion_Nombre = string.Empty;
		/// <summary />
		protected int _congregacion_Secuencia = -1;
		/// <summary />
		protected string _registro_Estado = string.Empty;
		/// <summary />
		protected DateTime _registro_Fecha = System.DateTime.MinValue;
		/// <summary />
		protected string _registro_Usuario = string.Empty;
		/// <summary />
		protected int _zona_Secuencia = -1;

		#endregion

		#region Property Navigation Holders

		/// <summary>
		/// The back navigation definition for walking [Congregaciones_Master]->[Personas_Master]
		/// Relationship Links: 
		/// [Congregaciones_Master.Congregacion_Secuencia = Personas_Master.Congregacion_Secuencia] (Required)
		/// <summary />
		protected Personas_MasterCollection _personas =  null;

		/// <summary>
		/// The navigation definition for walking [Congregaciones_Master]->[Circuitos_Cata]
		/// Relationship Links: 
		/// [Circuitos_Cata.Circuito_Numero = Congregaciones_Master.Circuito_Numero] (Required)
		protected OSIS.PEPPAM.BOM.Circuitos_Cata _circuito = null;

		/// <summary>
		/// The navigation definition for walking [Congregaciones_Master]->[Zonas_Master]
		/// Relationship Links: 
		/// [Zonas_Master.Zona_Secuencia = Congregaciones_Master.Zona_Secuencia] (Required)
		protected OSIS.PEPPAM.BOM.Zonas_Master _zona = null;


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(FieldNameConstants field)
		{
			switch (field)
			{
				case FieldNameConstants.Circuito_Numero:
					return 0;
				case FieldNameConstants.Congregacion_Direccion:
					return 150;
				case FieldNameConstants.Congregacion_Nombre:
					return 50;
				case FieldNameConstants.Congregacion_Secuencia:
					return 0;
				case FieldNameConstants.Registro_Estado:
					return 1;
				case FieldNameConstants.Registro_Fecha:
					return 0;
				case FieldNameConstants.Registro_Usuario:
					return 50;
				case FieldNameConstants.Zona_Secuencia:
					return 0;
			}
			return 0;
		}


		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(FieldNameConstants field)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type 'OSIS.PEPPAM.BOM.Entity.Congregaciones_Master.FieldNameConstants'.");

			switch ((FieldNameConstants)field)
			{
				case FieldNameConstants.Circuito_Numero: return typeof(int);
				case FieldNameConstants.Congregacion_Direccion: return typeof(string);
				case FieldNameConstants.Congregacion_Nombre: return typeof(string);
				case FieldNameConstants.Congregacion_Secuencia: return typeof(int);
				case FieldNameConstants.Registro_Estado: return typeof(string);
				case FieldNameConstants.Registro_Fecha: return typeof(DateTime);
				case FieldNameConstants.Registro_Usuario: return typeof(string);
				case FieldNameConstants.Zona_Secuencia: return typeof(int);
			}
			return null;
		}


		#endregion

		#region Get/Set Value


		#endregion

        public Congregaciones_Master()
        {
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
        }
        
		#region Properties

        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Congregacion_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Congregacion_Secuencia], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Congregacion_Secuencia")]
		public virtual int Congregacion_Secuencia
		{
			get { 
			return _congregacion_Secuencia; }
			set
			{
				if (value == _congregacion_Secuencia) return;
                this._congregacion_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Congregacion_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Circuito_Numero' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Circuito_Numero], Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Circuito_Numero")]
		public virtual int Circuito_Numero
		{
			get { 
if (((this._circuito_Numero == -1) 
                            && (this._circuito != null)))
                {
                    this._circuito_Numero = this._circuito.Circuito_Numero;
                }
			return _circuito_Numero; }
			set
			{
				if (value == _circuito_Numero) return;
                this._circuito = null;
				_circuito_Numero = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Circuito"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Circuito_Numero"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Zona_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Zona_Secuencia], Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Zona_Secuencia")]
		public virtual int Zona_Secuencia
		{
			get { 
if (((this._zona_Secuencia == -1) 
                            && (this._zona != null)))
                {
                    this._zona_Secuencia = this._zona.Zona_Secuencia;
                }
			return _zona_Secuencia; }
			set
			{
				if (value == _zona_Secuencia) return;
                this._zona = null;
				_zona_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Zona"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Zona_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Congregacion_Nombre' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Congregacion_Nombre], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Congregacion_Nombre")]
		public virtual string Congregacion_Nombre
		{
			get { 
			return _congregacion_Nombre; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Congregacion_Nombre))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Congregaciones_Master.Congregacion_Nombre", GetMaxLength(FieldNameConstants.Congregacion_Nombre)));
				if (value == _congregacion_Nombre) return;
                this._congregacion_Nombre = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Congregacion_Nombre"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Congregacion_Direccion' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Congregacion_Direccion], Field Length: 150, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Congregacion_Direccion")]
		public virtual string Congregacion_Direccion
		{
			get { 
			return _congregacion_Direccion; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Congregacion_Direccion))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Congregaciones_Master.Congregacion_Direccion", GetMaxLength(FieldNameConstants.Congregacion_Direccion)));
				if (value == _congregacion_Direccion) return;
                this._congregacion_Direccion = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Congregacion_Direccion"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Registro_Estado' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Registro_Estado], Field Length: 1, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Estado")]
		public virtual string Registro_Estado
		{
			get { 
			return _registro_Estado; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Estado))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Congregaciones_Master.Registro_Estado", GetMaxLength(FieldNameConstants.Registro_Estado)));
				if (value == _registro_Estado) return;
                this._registro_Estado = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Estado"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Registro_Fecha' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Registro_Fecha], Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(DateTime))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Fecha")]
		public virtual DateTime Registro_Fecha
		{
			get { 
			return _registro_Fecha; }
			set
			{
				if ((value < GlobalValues.MIN_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be less than " + GlobalValues.MIN_DATETIME.ToString());
				if ((value > GlobalValues.MAX_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be greater than " + GlobalValues.MAX_DATETIME.ToString());
				if (value == _registro_Fecha) return;
                this._registro_Fecha = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Fecha"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Congregaciones_Master.Registro_Usuario' field.
		/// </summary>
		/// <remarks>Field: [Congregaciones_Master].[Registro_Usuario], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Usuario")]
		public virtual string Registro_Usuario
		{
			get { 
			return _registro_Usuario; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Usuario))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Congregaciones_Master.Registro_Usuario", GetMaxLength(FieldNameConstants.Registro_Usuario)));
				if (value == _registro_Usuario) return;
                this._registro_Usuario = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Usuario"));
			}
		}


		#endregion

		#region Navigation Properties

		/// <summary>
		/// The back navigation definition for walking [Congregaciones_Master]->[Personas_Master]
		/// Relationship Links: 
		/// [Congregaciones_Master.Congregacion_Secuencia = Personas_Master.Congregacion_Secuencia] (Required)
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual OSIS.PEPPAM.BOM.Personas_MasterCollection Personas
        {
            get
            {
                if ((this._personas == null))
                {
                    if ((
                    (this.Congregacion_Secuencia == -1)
                       )
                         || (this.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) == true))
                    {
                        this._personas = new OSIS.PEPPAM.BOM.Personas_MasterCollection(this,null,null);
                        return this._personas;
                    }
                    this._personas = OSIS.PEPPAM.BOM.Personas_MasterCollection.LoadByCongregacion(this);
                }
                return this._personas;
            }
        }

		/// <summary>
		/// The navigation definition for walking [Congregaciones_Master]->[Circuitos_Cata]
		/// Relationship Links: 
		/// [Circuitos_Cata.Circuito_Numero = Congregaciones_Master.Circuito_Numero] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.BOM.Circuitos_Cata Circuito
		{
			get
			{
                if ((this._circuito == null))
                {
                    this._circuito = OSIS.PEPPAM.BOM.Circuitos_Cata.Load(Circuito_Numero);
                }
                return this._circuito;
			}
			set
            {
                _circuito_Numero = -1;
                this._circuito = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Circuito"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Circuito_Numero"));
            }
		}

		/// <summary>
		/// The navigation definition for walking [Congregaciones_Master]->[Zonas_Master]
		/// Relationship Links: 
		/// [Zonas_Master.Zona_Secuencia = Congregaciones_Master.Zona_Secuencia] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.BOM.Zonas_Master Zona
		{
			get
			{
                if ((this._zona == null))
                {
                    this._zona = OSIS.PEPPAM.BOM.Zonas_Master.Load(Zona_Secuencia);
                }
                return this._zona;
			}
			set
            {
                _zona_Secuencia = -1;
                this._zona = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Zona"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Zona_Secuencia"));
            }
		}

		#endregion

        public virtual string EntityKey
        {
            get
            {
                return this.Congregacion_Secuencia.ToString();
            }
            set
            {
               this.Congregacion_Secuencia = ((int)(ConvertUtilities.ChangeType(value, typeof(int), -1)));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Congregacion_Nombre.ToString();
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        [field:System.NonSerializedAttribute()]
        public event CodeFluent.Runtime.CodeFluentEntityActionEventHandler EntityAction;

        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }

        protected virtual void OnEntityAction(CodeFluent.Runtime.CodeFluentEntityActionEventArgs e)
        {
            if ((this.EntityAction != null))
            {
                this.EntityAction(this, e);
            }
        }

        string System.ComponentModel.IDataErrorInfo.Error
        {
            get
            {
                return this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.this[string columnName]
        {
            get
            {
                return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, this, columnName, null);
            }
        }
        
        public virtual CodeFluent.Runtime.CodeFluentEntityState EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<CodeFluent.Runtime.CodeFluentEntityState>.Default.Equals(value, this.EntityState) == true))
                {
                    return;
                }
                this._entityState = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("EntityState"));
            }
        }
        
        public virtual bool Equals(OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster)
        {
            if ((congregacionesMaster == null))
            {
                return false;
            }

            if (
                    (this.Congregacion_Secuencia == -1)
            )
            {
                return base.Equals(congregacionesMaster);
            }

 return ((
                    (this.Congregacion_Secuencia.Equals(congregacionesMaster.Congregacion_Secuencia))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster = null;
			 congregacionesMaster = obj as OSIS.PEPPAM.BOM.Congregaciones_Master;
            return this.Equals( congregacionesMaster);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        int System.IComparable.CompareTo(object value)
        {
            OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster = null;
             congregacionesMaster = value as OSIS.PEPPAM.BOM.Congregaciones_Master;
            if ((congregacionesMaster == null))
            {
                throw new System.ArgumentException("value");
            }
            int localCompareTo = this.CompareTo(congregacionesMaster);
            return localCompareTo;
        }

        public virtual int CompareTo(OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster)
        {
            if ((congregacionesMaster == null))
            {
                throw new System.ArgumentNullException("congregacionesMaster");
            }
            int localCompareTo = this.Congregacion_Secuencia.CompareTo(congregacionesMaster.Congregacion_Secuencia);
            return localCompareTo;
        }

        public virtual string Validate(System.Globalization.CultureInfo culture)
        {
            return CodeFluentPersistence.Validate(culture, this, null);
        }
        
        public virtual void Validate(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results);
            evt.Culture = culture;
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                string externalValidate;
                if ((evt.Argument != null))
                {
                    externalValidate = evt.Argument.ToString();
                }
                else
                {
                    externalValidate = OSIS.PEPPAM.BOM.Resources.Manager.GetStringWithDefault(culture, "OSIS.PEPPAM.BOM.Congregaciones_Master.ExternalValidate", "Type 'OSIS.PEPPAM.BOM.Congregaciones_Master' cannot be validated.", null);
                }
                CodeFluentPersistence.AddValidationError(results, externalValidate);
            }
            CodeFluentPersistence.ValidateMember(culture, results, this, null);
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results));
        }
        
        public void Validate()
        {
            string var = this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            if ((var != null))
            {
                throw new CodeFluent.Runtime.CodeFluentValidationException(var);
            }
        }
        
        string CodeFluent.Runtime.ICodeFluentValidator.Validate(System.Globalization.CultureInfo culture)
        {
            string localValidate = this.Validate(culture);
            return localValidate;
        }
        
        void CodeFluent.Runtime.ICodeFluentMemberValidator.Validate(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateMember(culture, memberName, results);
        }
        
        protected virtual void ValidateMember(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._circuito_Numero = CodeFluentPersistence.GetReaderValue(reader, "Circuito_Numero", (default(int)));
                this._congregacion_Direccion = CodeFluentPersistence.GetReaderValue(reader, "Congregacion_Direccion", (default(string)));
                this._congregacion_Nombre = CodeFluentPersistence.GetReaderValue(reader, "Congregacion_Nombre", (default(string)));
                this._congregacion_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Congregacion_Secuencia", (default(int)));
                this._registro_Estado = CodeFluentPersistence.GetReaderValue(reader, "Registro_Estado", (default(string)));
                this._registro_Fecha = CodeFluentPersistence.GetReaderValue(reader, "Registro_Fecha", (default(DateTime)));
                this._registro_Usuario = CodeFluentPersistence.GetReaderValue(reader, "Registro_Usuario", (default(string)));
                this._zona_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Zona_Secuencia", (default(int)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }

        protected virtual void ReadRecordOnSave(System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            //TODO: Puede ser que solo sean los Identity y no todo los primary keys
            this._congregacion_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Congregacion_Secuencia", ((int)(-1)));
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave(System.Data.IDataReader reader)
        {
            this.ReadRecordOnSave(reader);
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Congregaciones_Master Load(int congregacion_Secuencia)
        {
            if ((congregacion_Secuencia == default(int)))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster = new OSIS.PEPPAM.BOM.Congregaciones_Master();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Congregaciones_Master", null,  "Proc_Congregaciones_Master");
            persistence.AddRawParameter("@Congregacion_Secuencia", congregacion_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    congregacionesMaster.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
                    congregacionesMaster.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    return congregacionesMaster;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }

        public virtual bool Reload(CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            bool ret = false;
            if (
            (this.Congregacion_Secuencia == -1) 
              )
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Congregaciones_Master", null,  "Proc_Congregaciones_Master");
            persistence.AddRawParameter("@Congregacion_Secuencia", this.Congregacion_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecord(reader, options);
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    ret = true;
                }
                else
                {
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return ret;
        }

        protected virtual bool BaseSave(bool force)
        {
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted))
            {
                this.Delete();
                return false;
            }
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return false;
            }
            CodeFluentPersistence.ThrowIfDeleted(this);
            this.Validate();
            if (((force == false) 
                        && (this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged)))
            {
                return false;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Congregaciones_Master", "Editar");
            persistence.AddRawParameter("@Congregacion_Secuencia", Congregacion_Secuencia);
            persistence.AddRawParameter("@Circuito_Numero", Circuito_Numero);
            persistence.AddRawParameter("@Zona_Secuencia", Zona_Secuencia);
            persistence.AddRawParameter("@Congregacion_Nombre", Congregacion_Nombre);
            persistence.AddRawParameter("@Congregacion_Direccion", Congregacion_Direccion);
            persistence.AddRawParameter("@Registro_Estado", Registro_Estado);
            persistence.AddRawParameter("@Registro_Fecha", Registro_Fecha);
            persistence.AddRawParameter("@Registro_Usuario", Registro_Usuario);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecordOnSave(reader);
                }
                CodeFluentPersistence.NextResults(reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false));
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            return true;
        }
        
        public virtual bool Save()
        {
            bool localSave = this.BaseSave(false);
            return localSave;
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster)
        {
            if ((congregacionesMaster == null))
            {
                return false;
            }
            bool ret = congregacionesMaster.Save();
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster)
        {
            bool ret = OSIS.PEPPAM.BOM.Congregaciones_Master.Save(congregacionesMaster);
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster)
        {
            if ((congregacionesMaster == null))
            {
                return false;
            }
            bool ret = congregacionesMaster.Delete();
            return ret;
        }

        public virtual bool Delete()
        {
            bool ret = false;
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return ret;
            }
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Congregaciones_Master", "Borrar");
            persistence.AddRawParameter("@Congregacion_Secuencia", this.Congregacion_Secuencia);
            persistence.ExecuteNonQuery();
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false));
            ret = true;
            return ret;
        }

        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }

        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }

        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write("Circuito_Numero=");
            writer.Write(this.Circuito_Numero);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Congregacion_Direccion=");
            writer.Write(this.Congregacion_Direccion);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Congregacion_Nombre=");
            writer.Write(this.Congregacion_Nombre);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Congregacion_Secuencia=");
            writer.Write(this.Congregacion_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Estado=");
            writer.Write(this.Registro_Estado);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Fecha=");
            writer.Write(this.Registro_Fecha);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Usuario=");
            writer.Write(this.Registro_Usuario);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Zona_Secuencia=");
            writer.Write(this.Zona_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write(" Circuito=");
            if ((this._circuito != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._circuito)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(" Personas=");
            if ((this._personas != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._personas)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(" Zona=");
            if ((this._zona != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._zona)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(", EntityState=");
            writer.Write(this.EntityState);
            writer.Write("]");
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Congregaciones_Master LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Congregaciones_Master congregacionesMaster;
            System.Type[] types = new System.Type[] {
                    typeof(int)                    };
            object[] defaultValues = new object[] {
                    -1                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    int var0;            var0 = ((int)(v[0]));
            congregacionesMaster = OSIS.PEPPAM.BOM.Congregaciones_Master.Load( var0);
            return congregacionesMaster;
        }

        public  OSIS.PEPPAM.BOM.Congregaciones_Master Clone(bool deep)
        {
             OSIS.PEPPAM.BOM.Congregaciones_Master  congregacionesMaster = new  OSIS.PEPPAM.BOM.Congregaciones_Master();
            this.CopyTo(congregacionesMaster , deep);
            return congregacionesMaster ;
        }

        public OSIS.PEPPAM.BOM.Congregaciones_Master Clone()
        {
            OSIS.PEPPAM.BOM.Congregaciones_Master localClone = this.Clone(true);
            return localClone;
        }

        object System.ICloneable.Clone()
        {
            object localClone = this.Clone();
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Circuito_Numero") == true))
            {
                this.Circuito_Numero = ((int)(ConvertUtilities.ChangeType(dict["Circuito_Numero"], typeof(int), -1)));
            }
            if ((dict.Contains("Congregacion_Direccion") == true))
            {
                this.Congregacion_Direccion = ((string)(ConvertUtilities.ChangeType(dict["Congregacion_Direccion"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Congregacion_Nombre") == true))
            {
                this.Congregacion_Nombre = ((string)(ConvertUtilities.ChangeType(dict["Congregacion_Nombre"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Congregacion_Secuencia") == true))
            {
                this.Congregacion_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Congregacion_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Zona_Secuencia") == true))
            {
                this.Zona_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Zona_Secuencia"], typeof(int), -1)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict));
        }

        public virtual void CopyTo( OSIS.PEPPAM.BOM.Congregaciones_Master  congregacionesMaster, bool deep)
        {
            if ((congregacionesMaster == null))
            {
                throw new System.ArgumentNullException("congregacionesMaster");
            }
            congregacionesMaster.Circuito_Numero = this.Circuito_Numero;
            congregacionesMaster.Congregacion_Direccion = this.Congregacion_Direccion;
            congregacionesMaster.Congregacion_Nombre = this.Congregacion_Nombre;
            congregacionesMaster.Congregacion_Secuencia = this.Congregacion_Secuencia;
            congregacionesMaster.Registro_Estado = this.Registro_Estado;
            congregacionesMaster.Registro_Fecha = this.Registro_Fecha;
            congregacionesMaster.Registro_Usuario = this.Registro_Usuario;
            congregacionesMaster.Zona_Secuencia = this.Zona_Secuencia;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, congregacionesMaster));
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "circuito_numero": return "circuito_numero";
				case "congregacion_direccion": return "congregacion_direccion";
				case "congregacion_nombre": return "congregacion_nombre";
				case "congregacion_secuencia": return "congregacion_secuencia";
				case "registro_estado": return "registro_estado";
				case "registro_fecha": return "registro_fecha";
				case "registro_usuario": return "registro_usuario";
				case "zona_secuencia": return "zona_secuencia";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "circuito_numero": return "Congregaciones_Master";
				case "congregacion_direccion": return "Congregaciones_Master";
				case "congregacion_nombre": return "Congregaciones_Master";
				case "congregacion_secuencia": return "Congregaciones_Master";
				case "registro_estado": return "Congregaciones_Master";
				case "registro_fecha": return "Congregaciones_Master";
				case "registro_usuario": return "Congregaciones_Master";
				case "zona_secuencia": return "Congregaciones_Master";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "circuito_numero": return "Congregaciones_Master";
				case "congregacion_direccion": return "Congregaciones_Master";
				case "congregacion_nombre": return "Congregaciones_Master";
				case "congregacion_secuencia": return "Congregaciones_Master";
				case "registro_estado": return "Congregaciones_Master";
				case "registro_fecha": return "Congregaciones_Master";
				case "registro_usuario": return "Congregaciones_Master";
				case "zona_secuencia": return "Congregaciones_Master";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[circuito_numero\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[circuito_numero]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[congregacion_direccion\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[congregacion_direccion]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[congregacion_nombre\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[congregacion_nombre]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[congregacion_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[congregacion_secuencia]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_estado\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[registro_estado]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_fecha\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[registro_fecha]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_usuario\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[registro_usuario]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[zona_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Congregaciones_Master") + "].[zona_secuencia]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion


	}

}

