//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     Fecha :6/19/2014 1:29:30 PM
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OSIS.PEPPAM.BOM
{
    using System;
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    using System.Collections.Generic;
    
    
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class Personas_Notificaciones_TransCollection : System.Collections.IList, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> _baseList = new System.Collections.Generic.List<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        private int _totalRowCount = 0;
        
        [System.NonSerializedAttribute()]
        private OSIS.PEPPAM.BOM.Notificaciones_Master _notificaciones;
        [System.NonSerializedAttribute()]
        private OSIS.PEPPAM.BOM.Personas_Master _personas;
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> _blm852358831;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public Personas_Notificaciones_TransCollection()        {
            this._blm852358831 = new CodeFluent.Runtime.Utilities.BindingListManager<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>(this);
        }
        public Personas_Notificaciones_TransCollection(        OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones,        OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            this._blm852358831 = new CodeFluent.Runtime.Utilities.BindingListManager<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>(this);
            this._notificaciones = notificaciones;
            this._personas = personas;
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int TotalRowCount
        {
            get
            {
                return this._totalRowCount;
            }
            set
            {
                this._totalRowCount = value;
            }
        }
        
[System.Xml.Serialization.XmlIgnoreAttribute()]
        public OSIS.PEPPAM.BOM.Notificaciones_Master Notificaciones
        {
            get { return this._notificaciones; }
        }

[System.Xml.Serialization.XmlIgnoreAttribute()]
        public OSIS.PEPPAM.BOM.Personas_Master Personas
        {
            get { return this._personas; }
        }

        public OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans this[int index]
        {
            get
            {
                return ((OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)(value));
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm852358831.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm852358831.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm852358831.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm852358831.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm852358831.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm852358831.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm852358831.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm852358831.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(personasNotificacionesTrans);
            return localAdd;
        }
        
        protected virtual int BaseAdd(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                throw new System.ArgumentNullException("personasNotificacionesTrans");
            }
            if (
            (personasNotificacionesTrans.Persona_Secuencia == -1)
||            (personasNotificacionesTrans.Notificacion_Numero == -1)
                  )            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Persona_Secuencia,Notificacion_Numero", "personasNotificacionesTrans", "OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans");
            }
 if ((this._notificaciones != null))
            {
                personasNotificacionesTrans.Notificaciones = this._notificaciones;
            }
 if ((this._personas != null))
            {
                personasNotificacionesTrans.Personas = this._personas;
            }
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(personasNotificacionesTrans);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, personasNotificacionesTrans, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = null;
            try
            {
                personasNotificacionesTrans = ((OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((personasNotificacionesTrans == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(personasNotificacionesTrans);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>.Add(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            this.BaseAdd(personasNotificacionesTrans);
        }
        
        public virtual OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans AddByEntityKey(string key)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans.LoadByEntityKey(key);
            if (((personasNotificacionesTrans != null) 
                        && (this.Contains(personasNotificacionesTrans) == false)))
            {
                this.Add(personasNotificacionesTrans);
            }
            return personasNotificacionesTrans;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            bool localContains = this.BaseContains(personasNotificacionesTrans);
            return localContains;
        }
        
        protected virtual bool BaseContains(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                return false;
            }
            bool localContains = this.BaseList.Contains(personasNotificacionesTrans);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans;
			personasNotificacionesTrans = value as OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans;
            return this.Contains(personasNotificacionesTrans);
        }
        
        public int IndexOf(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            int localIndexOf = this.BaseIndexOf(personasNotificacionesTrans);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(personasNotificacionesTrans);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans;
			personasNotificacionesTrans = value as OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans;
            return this.IndexOf(personasNotificacionesTrans);
        }
        
        public void Insert(int index, OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            this.BaseInsert(index, personasNotificacionesTrans);
        }
        
        protected virtual void BaseInsert(int index, OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                throw new System.ArgumentNullException("personasNotificacionesTrans");
            }
            this.BaseList.Insert(index, personasNotificacionesTrans);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, personasNotificacionesTrans, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans;
			personasNotificacionesTrans = value as OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans;
            this.Insert(index, personasNotificacionesTrans);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = this[0];
                this.BaseRemove(personasNotificacionesTrans);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            return this.BaseRemove(personasNotificacionesTrans);
        }
        
        protected virtual bool BaseRemove(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                throw new System.ArgumentNullException("personasNotificacionesTrans");
            }
            int index = this.IndexOf(personasNotificacionesTrans);
if ((this._notificaciones != null))
            {
                personasNotificacionesTrans.Notificaciones = null;
            }
if ((this._personas != null))
            {
                personasNotificacionesTrans.Personas = null;
            }
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(personasNotificacionesTrans);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, personasNotificacionesTrans, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans;
			personasNotificacionesTrans = value as OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans;
            this.Remove(personasNotificacionesTrans);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans>.ListChangedTypeDeleting)), index));
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = this.BaseList[index];
if ((this._notificaciones != null))
            {
                personasNotificacionesTrans.Notificaciones = null;
            }
if ((this._personas != null))
            {
                personasNotificacionesTrans.Personas = null;
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, personasNotificacionesTrans, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = this[index];
                personasNotificacionesTrans.Save();
                if ((personasNotificacionesTrans.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(personasNotificacionesTrans);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
this._notificaciones = null;
this._personas = null;
            this.BaseList.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(personasNotificacionesTrans)).ReadRecord(reader);
                    if (true)
                    {
                        this.BaseAdd(personasNotificacionesTrans);
                        count = (count + 1);
                    }
                    personasNotificacionesTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection LoadAll()
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Notificaciones_Trans", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAll(null);
            return reader;
        }
        
  private void LoadByNotificaciones(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState notificacionesState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((notificaciones != null))
            {
                notificacionesState = notificaciones.EntityState;
            }
            this._notificaciones = notificaciones;
            this._personas = null;
            this.BaseList.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(0, pageSize, pageOptions, readCount) == true))
                {
                    OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(personasNotificacionesTrans)).ReadRecord(reader);
                    if (true)
                    {
                        this.BaseAdd(personasNotificacionesTrans);
                        count = (count + 1);
                    }
                    personasNotificacionesTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((notificaciones != null))
            {
                notificaciones.EntityState = notificacionesState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadByNotificaciones(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadByNotificaciones(pageOptions, notificaciones);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByNotificaciones(pageIndex, pageSize, pageOptions, reader, notificaciones);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection LoadByNotificaciones(OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadByNotificaciones(int.MinValue, int.MaxValue, null, notificaciones);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByNotificaciones(CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones)
        {
            if ((notificaciones == null))
            {
                return null;
            }
            if ((notificaciones.Notificacion_Numero == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Notificacion_Numero", "notificaciones", "OSIS.PEPPAM.BOM.Notificaciones_Master");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Notificaciones_Trans", "Notificaciones");
            persistence.AddRawParameter("@Notificacion_Numero", notificaciones.Notificacion_Numero);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByNotificaciones(OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones)
        {
            System.Data.IDataReader reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadByNotificaciones(null, notificaciones);
            return reader;
        }
 [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Personas_Notificaciones_TransCollection PageLoadByNotificaciones(int pageIndex, int pageSize,int notificacion_Numero)
        {
            OSIS.PEPPAM.BOM.Notificaciones_Master notificaciones = OSIS.PEPPAM.BOM.Notificaciones_Master.Load(notificacion_Numero);
            if ((notificaciones == null))
            {
                return new Personas_Notificaciones_TransCollection();
            }
            return Personas_Notificaciones_TransCollection.PageLoadByNotificaciones(pageIndex, pageSize, null, notificaciones);
        }
  private void LoadByPersonas(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader, OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            CodeFluent.Runtime.CodeFluentEntityState personasState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            if ((personas != null))
            {
                personasState = personas.EntityState;
            }
            this._personas = personas;
            this._notificaciones = null;
            this.BaseList.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(0, pageSize, pageOptions, readCount) == true))
                {
                    OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(personasNotificacionesTrans)).ReadRecord(reader);
                    if (true)
                    {
                        this.BaseAdd(personasNotificacionesTrans);
                        count = (count + 1);
                    }
                    personasNotificacionesTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
            if ((personas != null))
            {
                personas.EntityState = personasState;
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadByPersonas(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadByPersonas(pageOptions, personas);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadByPersonas(pageIndex, pageSize, pageOptions, reader, personas);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection LoadByPersonas(OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadByPersonas(int.MinValue, int.MaxValue, null, personas);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadByPersonas(CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            if ((personas == null))
            {
                return null;
            }
            if ((personas.Persona_Secuencia == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Persona_Secuencia", "personas", "OSIS.PEPPAM.BOM.Personas_Master");
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Notificaciones_Trans", "Personas");
            persistence.AddRawParameter("@Persona_Secuencia", personas.Persona_Secuencia);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadByPersonas(OSIS.PEPPAM.BOM.Personas_Master personas)
        {
            System.Data.IDataReader reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadByPersonas(null, personas);
            return reader;
        }
 [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static Personas_Notificaciones_TransCollection PageLoadByPersonas(int pageIndex, int pageSize,int persona_Secuencia)
        {
            OSIS.PEPPAM.BOM.Personas_Master personas = OSIS.PEPPAM.BOM.Personas_Master.Load(persona_Secuencia);
            if ((personas == null))
            {
                return new Personas_Notificaciones_TransCollection();
            }
            return Personas_Notificaciones_TransCollection.PageLoadByPersonas(pageIndex, pageSize, null, personas);
        }
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection Clone(bool deep)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm852358831.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans add = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans)(e.NewObject));
            if ((add == null))
            {
                add = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
            }
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm852358831.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm852358831.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm852358831.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm852358831.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                return false;
            }
            bool ret = personasNotificacionesTrans.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            bool ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans.Save(personasNotificacionesTrans);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans)
        {
            if ((personasNotificacionesTrans == null))
            {
                return false;
            }
            bool ret = personasNotificacionesTrans.Delete();
            return ret;
        }
    
    
        private void LoadAllPaging(int pageIndex, int pageSize, string searchString, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._notificaciones = null;
            this._personas = null;
            this.BaseList.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(0, pageSize, pageOptions, readCount) == true))
                {
                    this._totalRowCount = CodeFluentPersistence.GetReaderValue(reader, "TotalRowCount", 0);
                    OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(personasNotificacionesTrans)).ReadRecord(reader);
                    if (true)
                    {
                        this.BaseAdd(personasNotificacionesTrans);
                        count = (count + 1);
                    }
                    personasNotificacionesTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAllPaging(int pageIndex, int pageSize,string searchString, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAllPaging(pageIndex, pageSize, searchString, pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAllPaging(pageIndex, pageSize,searchString, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection LoadAllPaging(int pageIndex, int pageSize,string searchString)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAllPaging(pageIndex, pageSize,searchString, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAllPaging(int pageIndex, int pageSize, string searchString, CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Notificaciones_Trans", "Paging");
            persistence.AddParameter(string.Format("@PageIndex"), pageIndex);
            persistence.AddParameter(string.Format("@PageSize"), pageSize);
            persistence.AddParameter(string.Format("@SearchString" ), searchString);
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAllPaging(int pageIndex, int pageSize, string searchString)
        {
            System.Data.IDataReader reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAllPaging( pageIndex,  pageSize,  searchString,null);
            return reader;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAllPaging(int pageIndex, int pageSize, string searchString)
        {
            return OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAllPaging(pageIndex, pageSize, searchString, null);
        }
        
        private void LoadAllCustomPaging(int pageIndex, int pageSize, string searchString, string procName, Dictionary<string, string> parametes, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this._notificaciones = null;
            this._personas = null;
            this.BaseList.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(0, pageSize, pageOptions, readCount) == true))
                {
                    this._totalRowCount = CodeFluentPersistence.GetReaderValue(reader, "TotalRowCount", 0);
                    OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans personasNotificacionesTrans = new OSIS.PEPPAM.BOM.Personas_Notificaciones_Trans();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(personasNotificacionesTrans)).ReadRecord(reader);
                    if (true)
                    {
                        this.BaseAdd(personasNotificacionesTrans);
                        count = (count + 1);
                    }
                    personasNotificacionesTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAllCustomPaging(int pageIndex, int pageSize,string searchString, string procName, Dictionary<string, string> parametes, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = new OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAllCustomPaging(pageIndex, pageSize, searchString, procName, parametes, pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAllCustomPaging(pageIndex, pageSize,searchString, procName, parametes, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection LoadAllCustomPaging(int pageIndex, int pageSize,string searchString, string procName, Dictionary<string, string> parametes)
        {
            OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection ret = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAllCustomPaging(pageIndex, pageSize,searchString, procName, parametes, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAllCustomPaging(int pageIndex, int pageSize, string searchString, string procName, Dictionary<string, string> parametes, CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, procName, null, procName);
            persistence.AddParameter(string.Format("@PageIndex"), pageIndex);
            persistence.AddParameter(string.Format("@PageSize"), pageSize);
            persistence.AddParameter(string.Format("@SearchString" ), searchString);
            if ((parametes != null))
            {
                var enumerator = parametes.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    persistence.AddParameter(string.Format("@{0}", enumerator.Current.Key), enumerator.Current.Value);
                }
            }
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAllCustomPaging(int pageIndex, int pageSize, string searchString, string procName, Dictionary<string, string> parametes)
        {
            System.Data.IDataReader reader = OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageDataLoadAllCustomPaging( pageIndex,  pageSize,  searchString, procName, parametes, null);
            return reader;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection PageLoadAllCustomPaging(int pageIndex, int pageSize, string searchString, string procName, Dictionary<string, string> parametes)
        {
            return OSIS.PEPPAM.BOM.Personas_Notificaciones_TransCollection.PageLoadAllCustomPaging(pageIndex, pageSize, searchString, procName, parametes, null);
        }
        
    
    }
}

