//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Autor: Francisco
//     Fecha: 6/19/2014 1:29:30 PM
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
  using System.Text.RegularExpressions;
  using System.Collections.Generic;
namespace OSIS.PEPPAM.BOM
{
	/// <summary>
	/// The collection to hold 'Personas_Turnos_Trans' entities
	/// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MyWorkGenerators", "0.0.0.00000")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey},Persona_Turno_HC={Persona_Turno_HC}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.NameTypeConverter))]
	public partial class Personas_Turnos_Trans :  System.ICloneable, System.IComparable, System.IComparable<OSIS.PEPPAM.BOM.Personas_Turnos_Trans>, CodeFluent.Runtime.ICodeFluentEntity, System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable<OSIS.PEPPAM.BOM.Personas_Turnos_Trans>

	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'Personas_Turnos_Trans' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'Dia_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Dia_Secuencia' property")]
			Dia_Secuencia,
			/// <summary>
			/// Field mapping for the 'Horario_Turno_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Horario_Turno_Secuencia' property")]
			Horario_Turno_Secuencia,
			/// <summary>
			/// Field mapping for the 'Persona_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Persona_Secuencia' property")]
			Persona_Secuencia,
			/// <summary>
			/// Field mapping for the 'Persona_Turno_HC' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Persona_Turno_HC' property")]
			Persona_Turno_HC,
			/// <summary>
			/// Field mapping for the 'Registro_Estado' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Estado' property")]
			Registro_Estado,
			/// <summary>
			/// Field mapping for the 'Registro_Fecha' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Fecha' property")]
			Registro_Fecha,
			/// <summary>
			/// Field mapping for the 'Registro_Usuario' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Usuario' property")]
			Registro_Usuario,
		}
		#endregion

        private bool _raisePropertyChangedEvents = true;
        
        private CodeFluent.Runtime.CodeFluentEntityState _entityState;
        
		#region Property Holders

		/// <summary />
		protected int _dia_Secuencia = -1;
		/// <summary />
		protected int _horario_Turno_Secuencia = -1;
		/// <summary />
		protected int _persona_Secuencia = -1;
		/// <summary />
		protected string _persona_Turno_HC = string.Empty;
		/// <summary />
		protected string _registro_Estado = string.Empty;
		/// <summary />
		protected DateTime _registro_Fecha = System.DateTime.MinValue;
		/// <summary />
		protected string _registro_Usuario = string.Empty;

		#endregion

		#region Property Navigation Holders

		/// <summary>
		/// The back navigation definition for walking [Personas_Turnos_Trans]->[Experiencias_Master]
		/// Relationship Links: 
		/// [Personas_Turnos_Trans.Persona_Secuencia = Experiencias_Master.Persona_Secuencia] (Required)
		/// [Personas_Turnos_Trans.Horario_Turno_Secuencia = Experiencias_Master.Horario_Turno_Secuencia] (Required)
		/// [Personas_Turnos_Trans.Dia_Secuencia = Experiencias_Master.Dia_Secuencia] (Required)
		/// <summary />
		protected Experiencias_MasterCollection _experiencias_Master =  null;

		/// <summary>
		/// The navigation definition for walking [Personas_Turnos_Trans]->[Personas_Master]
		/// Relationship Links: 
		/// [Personas_Master.Persona_Secuencia = Personas_Turnos_Trans.Persona_Secuencia] (Required)
		protected OSIS.PEPPAM.BOM.Personas_Master _persona = null;

		/// <summary>
		/// The navigation definition for walking [Personas_Turnos_Trans]->[Horario_Turno_Dias_Trans]
		/// Relationship Links: 
		/// [Horario_Turno_Dias_Trans.Horario_Turno_Secuencia = Personas_Turnos_Trans.Horario_Turno_Secuencia] (Required)
		/// [Horario_Turno_Dias_Trans.Dia_Secuencia = Personas_Turnos_Trans.Dia_Secuencia] (Required)
		protected OSIS.PEPPAM.BOM.Horario_Turno_Dias_Trans _horario_Turno_Dias_Trans = null;


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(FieldNameConstants field)
		{
			switch (field)
			{
				case FieldNameConstants.Dia_Secuencia:
					return 0;
				case FieldNameConstants.Horario_Turno_Secuencia:
					return 0;
				case FieldNameConstants.Persona_Secuencia:
					return 0;
				case FieldNameConstants.Persona_Turno_HC:
					return 1;
				case FieldNameConstants.Registro_Estado:
					return 1;
				case FieldNameConstants.Registro_Fecha:
					return 0;
				case FieldNameConstants.Registro_Usuario:
					return 50;
			}
			return 0;
		}


		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(FieldNameConstants field)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type 'OSIS.PEPPAM.BOM.Entity.Personas_Turnos_Trans.FieldNameConstants'.");

			switch ((FieldNameConstants)field)
			{
				case FieldNameConstants.Dia_Secuencia: return typeof(int);
				case FieldNameConstants.Horario_Turno_Secuencia: return typeof(int);
				case FieldNameConstants.Persona_Secuencia: return typeof(int);
				case FieldNameConstants.Persona_Turno_HC: return typeof(string);
				case FieldNameConstants.Registro_Estado: return typeof(string);
				case FieldNameConstants.Registro_Fecha: return typeof(DateTime);
				case FieldNameConstants.Registro_Usuario: return typeof(string);
			}
			return null;
		}


		#endregion

		#region Get/Set Value


		#endregion

        public Personas_Turnos_Trans()
        {
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
        }
        
		#region Properties

        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Persona_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Persona_Secuencia], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Persona_Secuencia")]
		public virtual int Persona_Secuencia
		{
			get { 
if (((this._persona_Secuencia == -1) 
                            && (this._persona != null)))
                {
                    this._persona_Secuencia = this._persona.Persona_Secuencia;
                }
			return _persona_Secuencia; }
			set
			{
				if (value == _persona_Secuencia) return;
                this._persona = null;
				_persona_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Persona"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Persona_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Horario_Turno_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Horario_Turno_Secuencia], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Horario_Turno_Secuencia")]
		public virtual int Horario_Turno_Secuencia
		{
			get { 
if (((this._horario_Turno_Secuencia == -1) 
                            && (this._horario_Turno_Dias_Trans != null)))
                {
                    this._horario_Turno_Secuencia = this._horario_Turno_Dias_Trans.Horario_Turno_Secuencia;
                }
			return _horario_Turno_Secuencia; }
			set
			{
				if (value == _horario_Turno_Secuencia) return;
                this._horario_Turno_Dias_Trans = null;
				_horario_Turno_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("HorarioTurnoDiasTrans"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Horario_Turno_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Dia_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Dia_Secuencia], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Dia_Secuencia")]
		public virtual int Dia_Secuencia
		{
			get { 
if (((this._dia_Secuencia == -1) 
                            && (this._horario_Turno_Dias_Trans != null)))
                {
                    this._dia_Secuencia = this._horario_Turno_Dias_Trans.Dia_Secuencia;
                }
			return _dia_Secuencia; }
			set
			{
				if (value == _dia_Secuencia) return;
                this._horario_Turno_Dias_Trans = null;
				_dia_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("HorarioTurnoDiasTrans"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Dia_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Persona_Turno_HC' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Persona_Turno_HC], Field Length: 1, Not Nullable, Default Value: N</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Persona_Turno_HC")]
		public virtual string Persona_Turno_HC
		{
			get { 
			return _persona_Turno_HC; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Persona_Turno_HC))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Personas_Turnos_Trans.Persona_Turno_HC", GetMaxLength(FieldNameConstants.Persona_Turno_HC)));
				if (value == _persona_Turno_HC) return;
                this._persona_Turno_HC = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Persona_Turno_HC"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Registro_Estado' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Registro_Estado], Field Length: 1, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Estado")]
		public virtual string Registro_Estado
		{
			get { 
			return _registro_Estado; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Estado))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Personas_Turnos_Trans.Registro_Estado", GetMaxLength(FieldNameConstants.Registro_Estado)));
				if (value == _registro_Estado) return;
                this._registro_Estado = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Estado"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Registro_Fecha' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Registro_Fecha], Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(DateTime))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Fecha")]
		public virtual DateTime Registro_Fecha
		{
			get { 
			return _registro_Fecha; }
			set
			{
				if ((value < GlobalValues.MIN_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be less than " + GlobalValues.MIN_DATETIME.ToString());
				if ((value > GlobalValues.MAX_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be greater than " + GlobalValues.MAX_DATETIME.ToString());
				if (value == _registro_Fecha) return;
                this._registro_Fecha = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Fecha"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Personas_Turnos_Trans.Registro_Usuario' field.
		/// </summary>
		/// <remarks>Field: [Personas_Turnos_Trans].[Registro_Usuario], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Usuario")]
		public virtual string Registro_Usuario
		{
			get { 
			return _registro_Usuario; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Usuario))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Personas_Turnos_Trans.Registro_Usuario", GetMaxLength(FieldNameConstants.Registro_Usuario)));
				if (value == _registro_Usuario) return;
                this._registro_Usuario = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Usuario"));
			}
		}


		#endregion

		#region Navigation Properties

		/// <summary>
		/// The back navigation definition for walking [Personas_Turnos_Trans]->[Experiencias_Master]
		/// Relationship Links: 
		/// [Personas_Turnos_Trans.Persona_Secuencia = Experiencias_Master.Persona_Secuencia] (Required)
		/// [Personas_Turnos_Trans.Horario_Turno_Secuencia = Experiencias_Master.Horario_Turno_Secuencia] (Required)
		/// [Personas_Turnos_Trans.Dia_Secuencia = Experiencias_Master.Dia_Secuencia] (Required)
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual OSIS.PEPPAM.BOM.Experiencias_MasterCollection ExperienciasMaster
        {
            get
            {
                if ((this._experiencias_Master == null))
                {
                    if ((
                    (this.Persona_Secuencia == -1)
                    ||
                    (this.Horario_Turno_Secuencia == -1)
                    ||
                    (this.Dia_Secuencia == -1)
                       )
                         || (this.EntityState.Equals(CodeFluent.Runtime.CodeFluentEntityState.Created) == true))
                    {
                        this._experiencias_Master = new OSIS.PEPPAM.BOM.Experiencias_MasterCollection(null);
                        return this._experiencias_Master;
                    }
                    this._experiencias_Master = OSIS.PEPPAM.BOM.Experiencias_MasterCollection.LoadByPersonasTurnosTrans(this);
                }
                return this._experiencias_Master;
            }
        }

		/// <summary>
		/// The navigation definition for walking [Personas_Turnos_Trans]->[Personas_Master]
		/// Relationship Links: 
		/// [Personas_Master.Persona_Secuencia = Personas_Turnos_Trans.Persona_Secuencia] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.BOM.Personas_Master Persona
		{
			get
			{
                if ((this._persona == null))
                {
                    this._persona = OSIS.PEPPAM.BOM.Personas_Master.Load(Persona_Secuencia);
                }
                return this._persona;
			}
			set
            {
                _persona_Secuencia = -1;
                this._persona = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Persona"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Persona_Secuencia"));
            }
		}

		/// <summary>
		/// The navigation definition for walking [Personas_Turnos_Trans]->[Horario_Turno_Dias_Trans]
		/// Relationship Links: 
		/// [Horario_Turno_Dias_Trans.Horario_Turno_Secuencia = Personas_Turnos_Trans.Horario_Turno_Secuencia] (Required)
		/// [Horario_Turno_Dias_Trans.Dia_Secuencia = Personas_Turnos_Trans.Dia_Secuencia] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.BOM.Horario_Turno_Dias_Trans HorarioTurnoDiasTrans
		{
			get
			{
                if ((this._horario_Turno_Dias_Trans == null))
                {
                    this._horario_Turno_Dias_Trans = OSIS.PEPPAM.BOM.Horario_Turno_Dias_Trans.Load(Dia_Secuencia,Horario_Turno_Secuencia);
                }
                return this._horario_Turno_Dias_Trans;
			}
			set
            {
                _horario_Turno_Secuencia = -1;
                _dia_Secuencia = -1;
                this._horario_Turno_Dias_Trans = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("HorarioTurnoDiasTrans"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Horario_Turno_Secuencia"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Dia_Secuencia"));
            }
		}

		#endregion

        public virtual string EntityKey
        {
            get
            {
                object[] keys = new object[] {
                        this.Persona_Secuencia,
                        this.Horario_Turno_Secuencia,
                        this.Dia_Secuencia
                 };
                string v = CodeFluentPersistence.BuildEntityKey(keys);
                return v;
            }
            set
            {
                System.Type[] types = new System.Type[] {
                        typeof(int),
                        typeof(int),
                        typeof(int)
                        };
                object[] defaultValues = new object[] {
                        -1,
                        -1,
                        -1
                        };
                object[] v1 = CodeFluentPersistence.ParseEntityKey(value, types, defaultValues);
                this. Persona_Secuencia = ((int)(v1[0]));
                this. Horario_Turno_Secuencia = ((int)(v1[1]));
                this. Dia_Secuencia = ((int)(v1[2]));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Persona_Turno_HC.ToString();
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        [field:System.NonSerializedAttribute()]
        public event CodeFluent.Runtime.CodeFluentEntityActionEventHandler EntityAction;

        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }

        protected virtual void OnEntityAction(CodeFluent.Runtime.CodeFluentEntityActionEventArgs e)
        {
            if ((this.EntityAction != null))
            {
                this.EntityAction(this, e);
            }
        }

        string System.ComponentModel.IDataErrorInfo.Error
        {
            get
            {
                return this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.this[string columnName]
        {
            get
            {
                return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, this, columnName, null);
            }
        }
        
        public virtual CodeFluent.Runtime.CodeFluentEntityState EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<CodeFluent.Runtime.CodeFluentEntityState>.Default.Equals(value, this.EntityState) == true))
                {
                    return;
                }
                this._entityState = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("EntityState"));
            }
        }
        
        public virtual bool Equals(OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans)
        {
            if ((personasTurnosTrans == null))
            {
                return false;
            }

            if (
                    (this.Persona_Secuencia == -1)
                    ||
                    (this.Horario_Turno_Secuencia == -1)
                    ||
                    (this.Dia_Secuencia == -1)
            )
            {
                return base.Equals(personasTurnosTrans);
            }

 return ((
                    (this.Persona_Secuencia.Equals(personasTurnosTrans.Persona_Secuencia))
                    &&
                    (this.Horario_Turno_Secuencia.Equals(personasTurnosTrans.Horario_Turno_Secuencia))
                    &&
                    (this.Dia_Secuencia.Equals(personasTurnosTrans.Dia_Secuencia))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans = null;
			 personasTurnosTrans = obj as OSIS.PEPPAM.BOM.Personas_Turnos_Trans;
            return this.Equals( personasTurnosTrans);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        int System.IComparable.CompareTo(object value)
        {
            OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans = null;
             personasTurnosTrans = value as OSIS.PEPPAM.BOM.Personas_Turnos_Trans;
            if ((personasTurnosTrans == null))
            {
                throw new System.ArgumentException("value");
            }
            int localCompareTo = this.CompareTo(personasTurnosTrans);
            return localCompareTo;
        }

        public virtual int CompareTo(OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans)
        {
            if ((personasTurnosTrans == null))
            {
                throw new System.ArgumentNullException("personasTurnosTrans");
            }
            int localCompareTo = this.Persona_Secuencia.CompareTo(personasTurnosTrans.Persona_Secuencia);
            return localCompareTo;
        }

        public virtual string Validate(System.Globalization.CultureInfo culture)
        {
            return CodeFluentPersistence.Validate(culture, this, null);
        }
        
        public virtual void Validate(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results);
            evt.Culture = culture;
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                string externalValidate;
                if ((evt.Argument != null))
                {
                    externalValidate = evt.Argument.ToString();
                }
                else
                {
                    externalValidate = OSIS.PEPPAM.BOM.Resources.Manager.GetStringWithDefault(culture, "OSIS.PEPPAM.BOM.Personas_Turnos_Trans.ExternalValidate", "Type 'OSIS.PEPPAM.BOM.Personas_Turnos_Trans' cannot be validated.", null);
                }
                CodeFluentPersistence.AddValidationError(results, externalValidate);
            }
            CodeFluentPersistence.ValidateMember(culture, results, this, null);
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results));
        }
        
        public void Validate()
        {
            string var = this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            if ((var != null))
            {
                throw new CodeFluent.Runtime.CodeFluentValidationException(var);
            }
        }
        
        string CodeFluent.Runtime.ICodeFluentValidator.Validate(System.Globalization.CultureInfo culture)
        {
            string localValidate = this.Validate(culture);
            return localValidate;
        }
        
        void CodeFluent.Runtime.ICodeFluentMemberValidator.Validate(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateMember(culture, memberName, results);
        }
        
        protected virtual void ValidateMember(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._dia_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Dia_Secuencia", (default(int)));
                this._horario_Turno_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Horario_Turno_Secuencia", (default(int)));
                this._persona_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Persona_Secuencia", (default(int)));
                this._persona_Turno_HC = CodeFluentPersistence.GetReaderValue(reader, "Persona_Turno_HC", (default(string)));
                this._registro_Estado = CodeFluentPersistence.GetReaderValue(reader, "Registro_Estado", (default(string)));
                this._registro_Fecha = CodeFluentPersistence.GetReaderValue(reader, "Registro_Fecha", (default(DateTime)));
                this._registro_Usuario = CodeFluentPersistence.GetReaderValue(reader, "Registro_Usuario", (default(string)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }

        protected virtual void ReadRecordOnSave(System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            //TODO: Puede ser que solo sean los Identity y no todo los primary keys
            this._persona_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Persona_Secuencia", ((int)(-1)));
            //TODO: Puede ser que solo sean los Identity y no todo los primary keys
            this._horario_Turno_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Horario_Turno_Secuencia", ((int)(-1)));
            //TODO: Puede ser que solo sean los Identity y no todo los primary keys
            this._dia_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Dia_Secuencia", ((int)(-1)));
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave(System.Data.IDataReader reader)
        {
            this.ReadRecordOnSave(reader);
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Turnos_Trans Load(int persona_Secuencia,int horario_Turno_Secuencia,int dia_Secuencia)
        {
            if ((persona_Secuencia == default(int)))
            {
                return null;
            }
            if ((horario_Turno_Secuencia == default(int)))
            {
                return null;
            }
            if ((dia_Secuencia == default(int)))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans = new OSIS.PEPPAM.BOM.Personas_Turnos_Trans();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Turnos_Trans", null,  "Proc_Personas_Turnos_Trans");
            persistence.AddRawParameter("@Persona_Secuencia", persona_Secuencia);
            persistence.AddRawParameter("@Horario_Turno_Secuencia", horario_Turno_Secuencia);
            persistence.AddRawParameter("@Dia_Secuencia", dia_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    personasTurnosTrans.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
                    personasTurnosTrans.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    return personasTurnosTrans;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }

        public virtual bool Reload(CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            bool ret = false;
            if (
            (this.Persona_Secuencia == -1) 
||
            (this.Horario_Turno_Secuencia == -1) 
||
            (this.Dia_Secuencia == -1) 
              )
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Turnos_Trans", null,  "Proc_Personas_Turnos_Trans");
            persistence.AddRawParameter("@Persona_Secuencia", this.Persona_Secuencia);
            persistence.AddRawParameter("@Horario_Turno_Secuencia", this.Horario_Turno_Secuencia);
            persistence.AddRawParameter("@Dia_Secuencia", this.Dia_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecord(reader, options);
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    ret = true;
                }
                else
                {
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return ret;
        }

        protected virtual bool BaseSave(bool force)
        {
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted))
            {
                this.Delete();
                return false;
            }
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return false;
            }
            CodeFluentPersistence.ThrowIfDeleted(this);
            this.Validate();
            if (((force == false) 
                        && (this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged)))
            {
                return false;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Turnos_Trans", "Editar");
            persistence.AddRawParameter("@Persona_Secuencia", Persona_Secuencia);
            persistence.AddRawParameter("@Horario_Turno_Secuencia", Horario_Turno_Secuencia);
            persistence.AddRawParameter("@Dia_Secuencia", Dia_Secuencia);
            persistence.AddRawParameter("@Persona_Turno_HC", Persona_Turno_HC);
            persistence.AddRawParameter("@Registro_Estado", Registro_Estado);
            persistence.AddRawParameter("@Registro_Fecha", Registro_Fecha);
            persistence.AddRawParameter("@Registro_Usuario", Registro_Usuario);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecordOnSave(reader);
                }
                CodeFluentPersistence.NextResults(reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false));
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            return true;
        }
        
        public virtual bool Save()
        {
            bool localSave = this.BaseSave(false);
            return localSave;
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans)
        {
            if ((personasTurnosTrans == null))
            {
                return false;
            }
            bool ret = personasTurnosTrans.Save();
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans)
        {
            bool ret = OSIS.PEPPAM.BOM.Personas_Turnos_Trans.Save(personasTurnosTrans);
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans)
        {
            if ((personasTurnosTrans == null))
            {
                return false;
            }
            bool ret = personasTurnosTrans.Delete();
            return ret;
        }

        public virtual bool Delete()
        {
            bool ret = false;
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return ret;
            }
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Personas_Turnos_Trans", "Borrar");
            persistence.AddRawParameter("@Persona_Secuencia", this.Persona_Secuencia);
            persistence.AddRawParameter("@Horario_Turno_Secuencia", this.Horario_Turno_Secuencia);
            persistence.AddRawParameter("@Dia_Secuencia", this.Dia_Secuencia);
            persistence.ExecuteNonQuery();
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false));
            ret = true;
            return ret;
        }

        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }

        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }

        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write("Dia_Secuencia=");
            writer.Write(this.Dia_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Horario_Turno_Secuencia=");
            writer.Write(this.Horario_Turno_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Persona_Secuencia=");
            writer.Write(this.Persona_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Persona_Turno_HC=");
            writer.Write(this.Persona_Turno_HC);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Estado=");
            writer.Write(this.Registro_Estado);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Fecha=");
            writer.Write(this.Registro_Fecha);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Usuario=");
            writer.Write(this.Registro_Usuario);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write(" Persona=");
            if ((this._persona != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._persona)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(" HorarioTurnoDiasTrans=");
            if ((this._horario_Turno_Dias_Trans != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._horario_Turno_Dias_Trans)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(" ExperienciasMaster=");
            if ((this._experiencias_Master != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._experiencias_Master)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(", EntityState=");
            writer.Write(this.EntityState);
            writer.Write("]");
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Personas_Turnos_Trans LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Personas_Turnos_Trans personasTurnosTrans;
            System.Type[] types = new System.Type[] {
                    typeof(int),                    typeof(int),                    typeof(int)                    };
            object[] defaultValues = new object[] {
                    -1,                    -1,                    -1                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    int var0;            var0 = ((int)(v[0]));
                    int var1;            var1 = ((int)(v[1]));
                    int var2;            var2 = ((int)(v[2]));
            personasTurnosTrans = OSIS.PEPPAM.BOM.Personas_Turnos_Trans.Load( var0, var1, var2);
            return personasTurnosTrans;
        }

        public  OSIS.PEPPAM.BOM.Personas_Turnos_Trans Clone(bool deep)
        {
             OSIS.PEPPAM.BOM.Personas_Turnos_Trans  personasTurnosTrans = new  OSIS.PEPPAM.BOM.Personas_Turnos_Trans();
            this.CopyTo(personasTurnosTrans , deep);
            return personasTurnosTrans ;
        }

        public OSIS.PEPPAM.BOM.Personas_Turnos_Trans Clone()
        {
            OSIS.PEPPAM.BOM.Personas_Turnos_Trans localClone = this.Clone(true);
            return localClone;
        }

        object System.ICloneable.Clone()
        {
            object localClone = this.Clone();
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Dia_Secuencia") == true))
            {
                this.Dia_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Dia_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Horario_Turno_Secuencia") == true))
            {
                this.Horario_Turno_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Horario_Turno_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Persona_Secuencia") == true))
            {
                this.Persona_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Persona_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Persona_Turno_HC") == true))
            {
                this.Persona_Turno_HC = ((string)(ConvertUtilities.ChangeType(dict["Persona_Turno_HC"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict));
        }

        public virtual void CopyTo( OSIS.PEPPAM.BOM.Personas_Turnos_Trans  personasTurnosTrans, bool deep)
        {
            if ((personasTurnosTrans == null))
            {
                throw new System.ArgumentNullException("personasTurnosTrans");
            }
            personasTurnosTrans.Dia_Secuencia = this.Dia_Secuencia;
            personasTurnosTrans.Horario_Turno_Secuencia = this.Horario_Turno_Secuencia;
            personasTurnosTrans.Persona_Secuencia = this.Persona_Secuencia;
            personasTurnosTrans.Persona_Turno_HC = this.Persona_Turno_HC;
            personasTurnosTrans.Registro_Estado = this.Registro_Estado;
            personasTurnosTrans.Registro_Fecha = this.Registro_Fecha;
            personasTurnosTrans.Registro_Usuario = this.Registro_Usuario;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, personasTurnosTrans));
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "dia_secuencia": return "dia_secuencia";
				case "horario_turno_secuencia": return "horario_turno_secuencia";
				case "persona_secuencia": return "persona_secuencia";
				case "persona_turno_hc": return "persona_turno_hc";
				case "registro_estado": return "registro_estado";
				case "registro_fecha": return "registro_fecha";
				case "registro_usuario": return "registro_usuario";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "dia_secuencia": return "Personas_Turnos_Trans";
				case "horario_turno_secuencia": return "Personas_Turnos_Trans";
				case "persona_secuencia": return "Personas_Turnos_Trans";
				case "persona_turno_hc": return "Personas_Turnos_Trans";
				case "registro_estado": return "Personas_Turnos_Trans";
				case "registro_fecha": return "Personas_Turnos_Trans";
				case "registro_usuario": return "Personas_Turnos_Trans";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "dia_secuencia": return "Personas_Turnos_Trans";
				case "horario_turno_secuencia": return "Personas_Turnos_Trans";
				case "persona_secuencia": return "Personas_Turnos_Trans";
				case "persona_turno_hc": return "Personas_Turnos_Trans";
				case "registro_estado": return "Personas_Turnos_Trans";
				case "registro_fecha": return "Personas_Turnos_Trans";
				case "registro_usuario": return "Personas_Turnos_Trans";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[dia_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[dia_secuencia]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[horario_turno_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[horario_turno_secuencia]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[persona_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[persona_secuencia]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[persona_turno_hc\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[persona_turno_hc]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_estado\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[registro_estado]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_fecha\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[registro_fecha]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_usuario\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Personas_Turnos_Trans") + "].[registro_usuario]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion


	}

}

