//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Autor: Francisco
//     Fecha: 6/19/2014 1:29:30 PM
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Runtime.Serialization;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
 using System.Collections.Generic;
namespace OSIS.PEPPAM.BOM
{
    
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    public partial class Proc_Persona_Funcionalidades_Acciones : CodeFluent.Runtime.ICodeFluentLightEntity, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool _raisePropertyChangedEvents = true;

        
		#region Property Holders


		#endregion



        
        public Proc_Persona_Funcionalidades_Acciones()
        {
        }

        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
		#region Primitive Properties

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Codigo
		{
			get { return _funcionalidad_Accion_Codigo; }
			protected set
			{
				_funcionalidad_Accion_Codigo = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Codigo"));
			}
		}
		protected string _funcionalidad_Accion_Codigo = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Css
		{
			get { return _funcionalidad_Accion_Css; }
			protected set
			{
				_funcionalidad_Accion_Css = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Css"));
			}
		}
		protected string _funcionalidad_Accion_Css = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Descripcion
		{
			get { return _funcionalidad_Accion_Descripcion; }
			protected set
			{
				_funcionalidad_Accion_Descripcion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Descripcion"));
			}
		}
		protected string _funcionalidad_Accion_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Explicacion
		{
			get { return _funcionalidad_Accion_Explicacion; }
			protected set
			{
				_funcionalidad_Accion_Explicacion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Explicacion"));
			}
		}
		protected string _funcionalidad_Accion_Explicacion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Icono_Large
		{
			get { return _funcionalidad_Accion_Icono_Large; }
			protected set
			{
				_funcionalidad_Accion_Icono_Large = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Icono_Large"));
			}
		}
		protected string _funcionalidad_Accion_Icono_Large = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Icono_Small
		{
			get { return _funcionalidad_Accion_Icono_Small; }
			protected set
			{
				_funcionalidad_Accion_Icono_Small = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Icono_Small"));
			}
		}
		protected string _funcionalidad_Accion_Icono_Small = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Menu
		{
			get { return _funcionalidad_Accion_Menu; }
			protected set
			{
				_funcionalidad_Accion_Menu = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Menu"));
			}
		}
		protected string _funcionalidad_Accion_Menu = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(int?))]
		[DataMemberAttribute()]
		public int? Funcionalidad_Accion_Numero
		{
			get { return _funcionalidad_Accion_Numero; }
			protected set
			{
				_funcionalidad_Accion_Numero = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Numero"));
			}
		}
		protected int? _funcionalidad_Accion_Numero = -1;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Permiso_Descripcion
		{
			get { return _funcionalidad_Accion_Permiso_Descripcion; }
			protected set
			{
				_funcionalidad_Accion_Permiso_Descripcion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Permiso_Descripcion"));
			}
		}
		protected string _funcionalidad_Accion_Permiso_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Permiso_Necesita
		{
			get { return _funcionalidad_Accion_Permiso_Necesita; }
			protected set
			{
				_funcionalidad_Accion_Permiso_Necesita = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Permiso_Necesita"));
			}
		}
		protected string _funcionalidad_Accion_Permiso_Necesita = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(int?))]
		[DataMemberAttribute()]
		public int? Funcionalidad_Accion_Tipo_Secuencia
		{
			get { return _funcionalidad_Accion_Tipo_Secuencia; }
			protected set
			{
				_funcionalidad_Accion_Tipo_Secuencia = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Tipo_Secuencia"));
			}
		}
		protected int? _funcionalidad_Accion_Tipo_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Accion_Toolbar
		{
			get { return _funcionalidad_Accion_Toolbar; }
			protected set
			{
				_funcionalidad_Accion_Toolbar = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Accion_Toolbar"));
			}
		}
		protected string _funcionalidad_Accion_Toolbar = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Codigo
		{
			get { return _funcionalidad_Codigo; }
			protected set
			{
				_funcionalidad_Codigo = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Codigo"));
			}
		}
		protected string _funcionalidad_Codigo = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Nombre
		{
			get { return _funcionalidad_Nombre; }
			protected set
			{
				_funcionalidad_Nombre = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Nombre"));
			}
		}
		protected string _funcionalidad_Nombre = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Modulo_Nombre
		{
			get { return _modulo_Nombre; }
			protected set
			{
				_modulo_Nombre = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Modulo_Nombre"));
			}
		}
		protected string _modulo_Nombre = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(int?))]
		[DataMemberAttribute()]
		public int? Modulo_Numero
		{
			get { return _modulo_Numero; }
			protected set
			{
				_modulo_Numero = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Modulo_Numero"));
			}
		}
		protected int? _modulo_Numero = -1;

		#endregion

        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._funcionalidad_Accion_Codigo = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Codigo", ((string)(string.Empty)));
                this._funcionalidad_Accion_Css = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Css", ((string)(string.Empty)));
                this._funcionalidad_Accion_Descripcion = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Descripcion", ((string)(string.Empty)));
                this._funcionalidad_Accion_Explicacion = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Explicacion", ((string)(string.Empty)));
                this._funcionalidad_Accion_Icono_Large = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Icono_Large", ((string)(string.Empty)));
                this._funcionalidad_Accion_Icono_Small = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Icono_Small", ((string)(string.Empty)));
                this._funcionalidad_Accion_Menu = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Menu", ((string)(string.Empty)));
                this._funcionalidad_Accion_Numero = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Numero", ((int?)(-1)));
                this._funcionalidad_Accion_Permiso_Descripcion = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Permiso_Descripcion", ((string)(string.Empty)));
                this._funcionalidad_Accion_Permiso_Necesita = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Permiso_Necesita", ((string)(string.Empty)));
                this._funcionalidad_Accion_Tipo_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Tipo_Secuencia", ((int?)(-1)));
                this._funcionalidad_Accion_Toolbar = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Accion_Toolbar", ((string)(string.Empty)));
                this._funcionalidad_Codigo = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Codigo", ((string)(string.Empty)));
                this._funcionalidad_Nombre = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Nombre", ((string)(string.Empty)));
                this._modulo_Nombre = CodeFluentPersistence.GetReaderValue(reader, "Modulo_Nombre", ((string)(string.Empty)));
                this._modulo_Numero = CodeFluentPersistence.GetReaderValue(reader, "Modulo_Numero", ((int?)(-1)));
                this._totalRowCount = CodeFluentPersistence.GetReaderValue(reader, "TotalRowCount", ((int)(-1)));
            }
        }
        
        void CodeFluent.Runtime.ICodeFluentLightEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }
        private int _totalRowCount = 0;
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int TotalRowCount
        {
            get
            {
                return this._totalRowCount;
            }
            set
            {
                this._totalRowCount = value;
            }
        }
        

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones LoadOne(string funcionalidadAccionCodigo,string funcionalidadCodigo,int? personaSecuencia)
        {
            OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones  result = new OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Persona_Funcionalidades_Acciones", null, "Proc_Persona_Funcionalidades_Acciones");
            persistence.AddRawParameter("@Funcionalidad_Accion_Codigo", funcionalidadAccionCodigo);
            persistence.AddRawParameter("@Funcionalidad_Codigo", funcionalidadCodigo);
            if (personaSecuencia.HasValue)
            persistence.AddRawParameter("@Persona_Secuencia", personaSecuencia.Value);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    CodeFluent.Runtime.CodeFluentLightWeightPersistence.ReadRecord(reader, ((CodeFluent.Runtime.ICodeFluentLightEntity)(result)), null);
                    return result;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }


         public static System.Collections.Generic.List<OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones> Load(string funcionalidadAccionCodigo,string funcionalidadCodigo,int? personaSecuencia)
        {
            System.Collections.Generic.List<OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones> load = new System.Collections.Generic.List<OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones>();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Persona_Funcionalidades_Acciones", null, "Proc_Persona_Funcionalidades_Acciones");
            persistence.AddParameter("@Funcionalidad_Accion_Codigo", funcionalidadAccionCodigo);
            persistence.AddParameter("@Funcionalidad_Codigo", funcionalidadCodigo);
            persistence.AddParameter("@Persona_Secuencia", personaSecuencia);
            System.Data.IDataReader reader = null;
            bool readerRead;
            try
            {
                reader = persistence.ExecuteReader();
                for (readerRead = reader.Read(); (readerRead == true); readerRead = reader.Read())
                {
                    OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones _load = new OSIS.PEPPAM.BOM.Proc_Persona_Funcionalidades_Acciones();
                    CodeFluent.Runtime.CodeFluentLightWeightPersistence.ReadRecord(reader, ((CodeFluent.Runtime.ICodeFluentLightEntity)(_load)), null);
                    load.Add(_load);
                }
                return load;
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }

    }
}

