//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 5/4/2014 11:15:08 AM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Autor: Francisco
//     Fecha: 5/4/2014 11:15:08 AM
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using System.Runtime.Serialization;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
namespace OSIS.PEPPAM.BOM
{
    
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    public partial class Proc_Seguridad_Modulos_Funcionalidades : CodeFluent.Runtime.ICodeFluentLightEntity, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool _raisePropertyChangedEvents = true;

        
		#region Property Holders


		#endregion



        
        public Proc_Seguridad_Modulos_Funcionalidades()
        {
        }

        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
		#region Primitive Properties

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Codigo
		{
			get { return _funcionalidad_Codigo; }
			protected set
			{
				_funcionalidad_Codigo = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Codigo"));
			}
		}
		protected string _funcionalidad_Codigo = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Descripcion
		{
			get { return _funcionalidad_Descripcion; }
			protected set
			{
				_funcionalidad_Descripcion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Descripcion"));
			}
		}
		protected string _funcionalidad_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Explicacion
		{
			get { return _funcionalidad_Explicacion; }
			protected set
			{
				_funcionalidad_Explicacion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Explicacion"));
			}
		}
		protected string _funcionalidad_Explicacion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Nombre
		{
			get { return _funcionalidad_Nombre; }
			protected set
			{
				_funcionalidad_Nombre = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Nombre"));
			}
		}
		protected string _funcionalidad_Nombre = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(int?))]
		[DataMemberAttribute()]
		public int? Funcionalidad_Numero
		{
			get { return _funcionalidad_Numero; }
			protected set
			{
				_funcionalidad_Numero = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Numero"));
			}
		}
		protected int? _funcionalidad_Numero = -1;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Funcionalidad_Url
		{
			get { return _funcionalidad_Url; }
			protected set
			{
				_funcionalidad_Url = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Funcionalidad_Url"));
			}
		}
		protected string _funcionalidad_Url = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(int?))]
		[DataMemberAttribute()]
		public int? Modulo_Numero
		{
			get { return _modulo_Numero; }
			protected set
			{
				_modulo_Numero = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Modulo_Numero"));
			}
		}
		protected int? _modulo_Numero = -1;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Registro_Estado
		{
			get { return _registro_Estado; }
			protected set
			{
				_registro_Estado = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Estado"));
			}
		}
		protected string _registro_Estado = string.Empty;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(DateTime?))]
		[DataMemberAttribute()]
		public DateTime? Registro_Fecha
		{
			get { return _registro_Fecha; }
			protected set
			{
				_registro_Fecha = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Fecha"));
			}
		}
		protected DateTime? _registro_Fecha = System.DateTime.MinValue;

		/// <summary>
		/// 
		/// </summary>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
		[DataMemberAttribute()]
		public string Registro_Usuario
		{
			get { return _registro_Usuario; }
			protected set
			{
				_registro_Usuario = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Usuario"));
			}
		}
		protected string _registro_Usuario = string.Empty;

		#endregion

        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._funcionalidad_Codigo = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Codigo", ((string)(string.Empty)));
                this._funcionalidad_Descripcion = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Descripcion", ((string)(string.Empty)));
                this._funcionalidad_Explicacion = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Explicacion", ((string)(string.Empty)));
                this._funcionalidad_Nombre = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Nombre", ((string)(string.Empty)));
                this._funcionalidad_Numero = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Numero", ((int?)(-1)));
                this._funcionalidad_Url = CodeFluentPersistence.GetReaderValue(reader, "Funcionalidad_Url", ((string)(string.Empty)));
                this._modulo_Numero = CodeFluentPersistence.GetReaderValue(reader, "Modulo_Numero", ((int?)(-1)));
                this._registro_Estado = CodeFluentPersistence.GetReaderValue(reader, "Registro_Estado", ((string)(string.Empty)));
                this._registro_Fecha = CodeFluentPersistence.GetReaderValue(reader, "Registro_Fecha", ((DateTime?)(System.DateTime.MinValue)));
                this._registro_Usuario = CodeFluentPersistence.GetReaderValue(reader, "Registro_Usuario", ((string)(string.Empty)));
            }
        }
        
        void CodeFluent.Runtime.ICodeFluentLightEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }
    }
}

