//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     Autor: Francisco
//     Fecha: 6/19/2014 1:29:30 PM
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
  using System.Text.RegularExpressions;
  using System.Collections.Generic;
namespace OSIS.PEPPAM.BOM
{
	/// <summary>
	/// The collection to hold 'Registro_Preguntas_Cata' entities
	/// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MyWorkGenerators", "0.0.0.00000")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey},Pregunta_Descripcion={Pregunta_Descripcion}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.NameTypeConverter))]
	public partial class Registro_Preguntas_Cata :  System.ICloneable, System.IComparable, System.IComparable<OSIS.PEPPAM.BOM.Registro_Preguntas_Cata>, CodeFluent.Runtime.ICodeFluentEntity, System.ComponentModel.IDataErrorInfo, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, System.IEquatable<OSIS.PEPPAM.BOM.Registro_Preguntas_Cata>

	{
		#region FieldNameConstants Enumeration

		/// <summary>
		/// Enumeration to define each property that maps to a database field for the 'Registro_Preguntas_Cata' table.
		/// </summary>
		public enum FieldNameConstants
		{
			/// <summary>
			/// Field mapping for the 'Pregunta_Descripcion' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Pregunta_Descripcion' property")]
			Pregunta_Descripcion,
			/// <summary>
			/// Field mapping for the 'Pregunta_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Pregunta_Secuencia' property")]
			Pregunta_Secuencia,
			/// <summary>
			/// Field mapping for the 'Registro_Estado' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Estado' property")]
			Registro_Estado,
			/// <summary>
			/// Field mapping for the 'Registro_Fecha' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Fecha' property")]
			Registro_Fecha,
			/// <summary>
			/// Field mapping for the 'Registro_Usuario' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Registro_Usuario' property")]
			Registro_Usuario,
			/// <summary>
			/// Field mapping for the 'Respuesta_Secuencia' property
			/// </summary>
			[System.ComponentModel.Description("Field mapping for the 'Respuesta_Secuencia' property")]
			Respuesta_Secuencia,
		}
		#endregion

        private bool _raisePropertyChangedEvents = true;
        
        private CodeFluent.Runtime.CodeFluentEntityState _entityState;
        
		#region Property Holders

		/// <summary />
		protected string _pregunta_Descripcion = string.Empty;
		/// <summary />
		protected int _pregunta_Secuencia = -1;
		/// <summary />
		protected string _registro_Estado = string.Empty;
		/// <summary />
		protected DateTime _registro_Fecha = System.DateTime.MinValue;
		/// <summary />
		protected string _registro_Usuario = string.Empty;
		/// <summary />
		protected int _respuesta_Secuencia = -1;

		#endregion

		#region Property Navigation Holders

		/// <summary>
		/// The navigation definition for walking [Registro_Preguntas_Cata]->[Registro_Respuestas_Cata]
		/// Relationship Links: 
		/// [Registro_Respuestas_Cata.Respuesta_Secuencia = Registro_Preguntas_Cata.Respuesta_Secuencia] (Required)
		protected OSIS.PEPPAM.BOM.Registro_Respuestas_Cata _registro_Respuestas_Cata = null;


		#endregion

		#region GetMaxLength

		/// <summary>
		/// Gets the maximum size of the field value.
		/// </summary>
		public static int GetMaxLength(FieldNameConstants field)
		{
			switch (field)
			{
				case FieldNameConstants.Pregunta_Descripcion:
					return 500;
				case FieldNameConstants.Pregunta_Secuencia:
					return 0;
				case FieldNameConstants.Registro_Estado:
					return 1;
				case FieldNameConstants.Registro_Fecha:
					return 0;
				case FieldNameConstants.Registro_Usuario:
					return 50;
				case FieldNameConstants.Respuesta_Secuencia:
					return 0;
			}
			return 0;
		}


		#endregion

		#region GetFieldType

		/// <summary>
		/// Gets the system type of a field on this object
		/// </summary>
		public static System.Type GetFieldType(FieldNameConstants field)
		{
			if (field.GetType() != typeof(FieldNameConstants))
				throw new Exception("The '" + field.GetType().ReflectedType.ToString() + ".FieldNameConstants' value is not valid. The field parameter must be of type 'OSIS.PEPPAM.BOM.Entity.Registro_Preguntas_Cata.FieldNameConstants'.");

			switch ((FieldNameConstants)field)
			{
				case FieldNameConstants.Pregunta_Descripcion: return typeof(string);
				case FieldNameConstants.Pregunta_Secuencia: return typeof(int);
				case FieldNameConstants.Registro_Estado: return typeof(string);
				case FieldNameConstants.Registro_Fecha: return typeof(DateTime);
				case FieldNameConstants.Registro_Usuario: return typeof(string);
				case FieldNameConstants.Respuesta_Secuencia: return typeof(int);
			}
			return null;
		}


		#endregion

		#region Get/Set Value


		#endregion

        public Registro_Preguntas_Cata()
        {
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
        }
        
		#region Properties

        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Pregunta_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Pregunta_Secuencia], Not Nullable, Primary Key, Unique, Indexed</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Pregunta_Secuencia")]
		public virtual int Pregunta_Secuencia
		{
			get { 
			return _pregunta_Secuencia; }
			set
			{
				if (value == _pregunta_Secuencia) return;
                this._pregunta_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Pregunta_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Respuesta_Secuencia' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Respuesta_Secuencia], Not Nullable, Default Value: 1</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(int))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Respuesta_Secuencia")]
		public virtual int Respuesta_Secuencia
		{
			get { 
if (((this._respuesta_Secuencia == -1) 
                            && (this._registro_Respuestas_Cata != null)))
                {
                    this._respuesta_Secuencia = this._registro_Respuestas_Cata.Respuesta_Secuencia;
                }
			return _respuesta_Secuencia; }
			set
			{
				if (value == _respuesta_Secuencia) return;
                this._registro_Respuestas_Cata = null;
				_respuesta_Secuencia = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("RegistroRespuestasCata"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Respuesta_Secuencia"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Pregunta_Descripcion' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Pregunta_Descripcion], Field Length: 500, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Pregunta_Descripcion")]
		public virtual string Pregunta_Descripcion
		{
			get { 
			return _pregunta_Descripcion; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Pregunta_Descripcion))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Registro_Preguntas_Cata.Pregunta_Descripcion", GetMaxLength(FieldNameConstants.Pregunta_Descripcion)));
				if (value == _pregunta_Descripcion) return;
                this._pregunta_Descripcion = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Pregunta_Descripcion"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Registro_Estado' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Registro_Estado], Field Length: 1, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Estado")]
		public virtual string Registro_Estado
		{
			get { 
			return _registro_Estado; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Estado))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Registro_Preguntas_Cata.Registro_Estado", GetMaxLength(FieldNameConstants.Registro_Estado)));
				if (value == _registro_Estado) return;
                this._registro_Estado = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Estado"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Registro_Fecha' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Registro_Fecha], Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(DateTime))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Fecha")]
		public virtual DateTime Registro_Fecha
		{
			get { 
			return _registro_Fecha; }
			set
			{
				if ((value < GlobalValues.MIN_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be less than " + GlobalValues.MIN_DATETIME.ToString());
				if ((value > GlobalValues.MAX_DATETIME)) throw new Exception("The DateTime value 'Registro_Fecha' (" + value.ToString("yyyy-MM-dd HH:mm:ss") + ") cannot be greater than " + GlobalValues.MAX_DATETIME.ToString());
				if (value == _registro_Fecha) return;
                this._registro_Fecha = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Fecha"));
			}
		}

		/// <summary>
		/// The property that maps back to the database 'Registro_Preguntas_Cata.Registro_Usuario' field.
		/// </summary>
		/// <remarks>Field: [Registro_Preguntas_Cata].[Registro_Usuario], Field Length: 50, Not Nullable</remarks>
		[System.ComponentModel.Browsable(true)]
		[System.Xml.Serialization.XmlElementAttribute(IsNullable = false, Type=typeof(string))]
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		[System.ComponentModel.DisplayName("Registro_Usuario")]
		public virtual string Registro_Usuario
		{
			get { 
			return _registro_Usuario; }
			set
			{
				if ((value != null) && (value.Length > GetMaxLength(FieldNameConstants.Registro_Usuario))) throw new Exception(string.Format(GlobalValues.ERROR_DATA_TOO_BIG, value, "Registro_Preguntas_Cata.Registro_Usuario", GetMaxLength(FieldNameConstants.Registro_Usuario)));
				if (value == _registro_Usuario) return;
                this._registro_Usuario = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Registro_Usuario"));
			}
		}


		#endregion

		#region Navigation Properties

		/// <summary>
		/// The navigation definition for walking [Registro_Preguntas_Cata]->[Registro_Respuestas_Cata]
		/// Relationship Links: 
		/// [Registro_Respuestas_Cata.Respuesta_Secuencia = Registro_Preguntas_Cata.Respuesta_Secuencia] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.BOM.Registro_Respuestas_Cata RegistroRespuestasCata
		{
			get
			{
                if ((this._registro_Respuestas_Cata == null))
                {
                    this._registro_Respuestas_Cata = OSIS.PEPPAM.BOM.Registro_Respuestas_Cata.Load(Respuesta_Secuencia);
                }
                return this._registro_Respuestas_Cata;
			}
			set
            {
                _respuesta_Secuencia = -1;
                this._registro_Respuestas_Cata = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("RegistroRespuestasCata"));
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Respuesta_Secuencia"));
            }
		}

		#endregion

        public virtual string EntityKey
        {
            get
            {
                return this.Pregunta_Secuencia.ToString();
            }
            set
            {
               this.Pregunta_Secuencia = ((int)(ConvertUtilities.ChangeType(value, typeof(int), -1)));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Pregunta_Descripcion.ToString();
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        [field:System.NonSerializedAttribute()]
        public event CodeFluent.Runtime.CodeFluentEntityActionEventHandler EntityAction;

        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }

        protected virtual void OnEntityAction(CodeFluent.Runtime.CodeFluentEntityActionEventArgs e)
        {
            if ((this.EntityAction != null))
            {
                this.EntityAction(this, e);
            }
        }

        string System.ComponentModel.IDataErrorInfo.Error
        {
            get
            {
                return this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.this[string columnName]
        {
            get
            {
                return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, this, columnName, null);
            }
        }
        
        public virtual CodeFluent.Runtime.CodeFluentEntityState EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<CodeFluent.Runtime.CodeFluentEntityState>.Default.Equals(value, this.EntityState) == true))
                {
                    return;
                }
                this._entityState = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("EntityState"));
            }
        }
        
        public virtual bool Equals(OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata)
        {
            if ((registroPreguntasCata == null))
            {
                return false;
            }

            if (
                    (this.Pregunta_Secuencia == -1)
            )
            {
                return base.Equals(registroPreguntasCata);
            }

 return ((
                    (this.Pregunta_Secuencia.Equals(registroPreguntasCata.Pregunta_Secuencia))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata = null;
			 registroPreguntasCata = obj as OSIS.PEPPAM.BOM.Registro_Preguntas_Cata;
            return this.Equals( registroPreguntasCata);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        int System.IComparable.CompareTo(object value)
        {
            OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata = null;
             registroPreguntasCata = value as OSIS.PEPPAM.BOM.Registro_Preguntas_Cata;
            if ((registroPreguntasCata == null))
            {
                throw new System.ArgumentException("value");
            }
            int localCompareTo = this.CompareTo(registroPreguntasCata);
            return localCompareTo;
        }

        public virtual int CompareTo(OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata)
        {
            if ((registroPreguntasCata == null))
            {
                throw new System.ArgumentNullException("registroPreguntasCata");
            }
            int localCompareTo = this.Pregunta_Secuencia.CompareTo(registroPreguntasCata.Pregunta_Secuencia);
            return localCompareTo;
        }

        public virtual string Validate(System.Globalization.CultureInfo culture)
        {
            return CodeFluentPersistence.Validate(culture, this, null);
        }
        
        public virtual void Validate(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results);
            evt.Culture = culture;
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                string externalValidate;
                if ((evt.Argument != null))
                {
                    externalValidate = evt.Argument.ToString();
                }
                else
                {
                    externalValidate = OSIS.PEPPAM.BOM.Resources.Manager.GetStringWithDefault(culture, "OSIS.PEPPAM.BOM.Registro_Preguntas_Cata.ExternalValidate", "Type 'OSIS.PEPPAM.BOM.Registro_Preguntas_Cata' cannot be validated.", null);
                }
                CodeFluentPersistence.AddValidationError(results, externalValidate);
            }
            CodeFluentPersistence.ValidateMember(culture, results, this, null);
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results));
        }
        
        public void Validate()
        {
            string var = this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            if ((var != null))
            {
                throw new CodeFluent.Runtime.CodeFluentValidationException(var);
            }
        }
        
        string CodeFluent.Runtime.ICodeFluentValidator.Validate(System.Globalization.CultureInfo culture)
        {
            string localValidate = this.Validate(culture);
            return localValidate;
        }
        
        void CodeFluent.Runtime.ICodeFluentMemberValidator.Validate(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateMember(culture, memberName, results);
        }
        
        protected virtual void ValidateMember(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
        }
        
        protected virtual void ReadRecord(System.Data.IDataReader reader, CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                this._pregunta_Descripcion = CodeFluentPersistence.GetReaderValue(reader, "Pregunta_Descripcion", (default(string)));
                this._pregunta_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Pregunta_Secuencia", (default(int)));
                this._registro_Estado = CodeFluentPersistence.GetReaderValue(reader, "Registro_Estado", (default(string)));
                this._registro_Fecha = CodeFluentPersistence.GetReaderValue(reader, "Registro_Fecha", (default(DateTime)));
                this._registro_Usuario = CodeFluentPersistence.GetReaderValue(reader, "Registro_Usuario", (default(string)));
                this._respuesta_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Respuesta_Secuencia", (default(int)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecord, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecord(System.Data.IDataReader reader)
        {
            this.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
        }

        protected virtual void ReadRecordOnSave(System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            //TODO: Puede ser que solo sean los Identity y no todo los primary keys
            this._pregunta_Secuencia = CodeFluentPersistence.GetReaderValue(reader, "Pregunta_Secuencia", ((int)(-1)));
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.ReadRecordOnSave, false, false));
        }

        void CodeFluent.Runtime.ICodeFluentEntity.ReadRecordOnSave(System.Data.IDataReader reader)
        {
            this.ReadRecordOnSave(reader);
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Registro_Preguntas_Cata Load(int pregunta_Secuencia)
        {
            if ((pregunta_Secuencia == default(int)))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata = new OSIS.PEPPAM.BOM.Registro_Preguntas_Cata();
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Registro_Preguntas_Cata", null,  "Proc_Registro_Preguntas_Cata");
            persistence.AddRawParameter("@Pregunta_Secuencia", pregunta_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    registroPreguntasCata.ReadRecord(reader, CodeFluent.Runtime.CodeFluentReloadOptions.Default);
                    registroPreguntasCata.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    return registroPreguntasCata;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return null;
        }

        public virtual bool Reload(CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            bool ret = false;
            if (
            (this.Pregunta_Secuencia == -1) 
              )
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Registro_Preguntas_Cata", null,  "Proc_Registro_Preguntas_Cata");
            persistence.AddRawParameter("@Pregunta_Secuencia", this.Pregunta_Secuencia);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecord(reader, options);
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                    ret = true;
                }
                else
                {
                    this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
                }
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            return ret;
        }

        protected virtual bool BaseSave(bool force)
        {
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted))
            {
                this.Delete();
                return false;
            }
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saving, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return false;
            }
            CodeFluentPersistence.ThrowIfDeleted(this);
            this.Validate();
            if (((force == false) 
                        && (this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged)))
            {
                return false;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Registro_Preguntas_Cata", "Editar");
            persistence.AddRawParameter("@Pregunta_Secuencia", Pregunta_Secuencia);
            persistence.AddRawParameter("@Respuesta_Secuencia", Respuesta_Secuencia);
            persistence.AddRawParameter("@Pregunta_Descripcion", Pregunta_Descripcion);
            persistence.AddRawParameter("@Registro_Estado", Registro_Estado);
            persistence.AddRawParameter("@Registro_Fecha", Registro_Fecha);
            persistence.AddRawParameter("@Registro_Usuario", Registro_Usuario);
            System.Data.IDataReader reader = null;
            try
            {
                reader = persistence.ExecuteReader();
                if ((reader.Read() == true))
                {
                    this.ReadRecordOnSave(reader);
                }
                CodeFluentPersistence.NextResults(reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                persistence.CompleteCommand();
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Saved, false, false));
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            return true;
        }
        
        public virtual bool Save()
        {
            bool localSave = this.BaseSave(false);
            return localSave;
        }
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata)
        {
            if ((registroPreguntasCata == null))
            {
                return false;
            }
            bool ret = registroPreguntasCata.Save();
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata)
        {
            bool ret = OSIS.PEPPAM.BOM.Registro_Preguntas_Cata.Save(registroPreguntasCata);
            return ret;
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata)
        {
            if ((registroPreguntasCata == null))
            {
                return false;
            }
            bool ret = registroPreguntasCata.Delete();
            return ret;
        }

        public virtual bool Delete()
        {
            bool ret = false;
            CodeFluent.Runtime.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleting, true);
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                return ret;
            }
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
            {
                return ret;
            }
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(OSIS.PEPPAM.BOM.Constants.OSIS_PEPPAM_BOMStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "Proc_Registro_Preguntas_Cata", "Borrar");
            persistence.AddRawParameter("@Pregunta_Secuencia", this.Pregunta_Secuencia);
            persistence.ExecuteNonQuery();
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Deleted;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Deleted, false, false));
            ret = true;
            return ret;
        }

        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }

        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }

        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write("Pregunta_Descripcion=");
            writer.Write(this.Pregunta_Descripcion);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Pregunta_Secuencia=");
            writer.Write(this.Pregunta_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Estado=");
            writer.Write(this.Registro_Estado);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Fecha=");
            writer.Write(this.Registro_Fecha);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Registro_Usuario=");
            writer.Write(this.Registro_Usuario);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write("Respuesta_Secuencia=");
            writer.Write(this.Respuesta_Secuencia);
            writer.Write(",");
            writer.WriteLine("");
            writer.Write(" RegistroRespuestasCata=");
            if ((this._registro_Respuestas_Cata != null))
            {
                ((CodeFluent.Runtime.ICodeFluentObject)(this._registro_Respuestas_Cata)).Trace(writer);
            }
            else
            {
                writer.Write("<null>");
            }
            writer.Write(",");
            writer.Write(", EntityState=");
            writer.Write(this.EntityState);
            writer.Write("]");
        }

        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static OSIS.PEPPAM.BOM.Registro_Preguntas_Cata LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.BOM.Registro_Preguntas_Cata registroPreguntasCata;
            System.Type[] types = new System.Type[] {
                    typeof(int)                    };
            object[] defaultValues = new object[] {
                    -1                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    int var0;            var0 = ((int)(v[0]));
            registroPreguntasCata = OSIS.PEPPAM.BOM.Registro_Preguntas_Cata.Load( var0);
            return registroPreguntasCata;
        }

        public  OSIS.PEPPAM.BOM.Registro_Preguntas_Cata Clone(bool deep)
        {
             OSIS.PEPPAM.BOM.Registro_Preguntas_Cata  registroPreguntasCata = new  OSIS.PEPPAM.BOM.Registro_Preguntas_Cata();
            this.CopyTo(registroPreguntasCata , deep);
            return registroPreguntasCata ;
        }

        public OSIS.PEPPAM.BOM.Registro_Preguntas_Cata Clone()
        {
            OSIS.PEPPAM.BOM.Registro_Preguntas_Cata localClone = this.Clone(true);
            return localClone;
        }

        object System.ICloneable.Clone()
        {
            object localClone = this.Clone();
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Pregunta_Descripcion") == true))
            {
                this.Pregunta_Descripcion = ((string)(ConvertUtilities.ChangeType(dict["Pregunta_Descripcion"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Pregunta_Secuencia") == true))
            {
                this.Pregunta_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Pregunta_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Respuesta_Secuencia") == true))
            {
                this.Respuesta_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Respuesta_Secuencia"], typeof(int), -1)));
            }
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict));
        }

        public virtual void CopyTo( OSIS.PEPPAM.BOM.Registro_Preguntas_Cata  registroPreguntasCata, bool deep)
        {
            if ((registroPreguntasCata == null))
            {
                throw new System.ArgumentNullException("registroPreguntasCata");
            }
            registroPreguntasCata.Pregunta_Descripcion = this.Pregunta_Descripcion;
            registroPreguntasCata.Pregunta_Secuencia = this.Pregunta_Secuencia;
            registroPreguntasCata.Registro_Estado = this.Registro_Estado;
            registroPreguntasCata.Registro_Fecha = this.Registro_Fecha;
            registroPreguntasCata.Registro_Usuario = this.Registro_Usuario;
            registroPreguntasCata.Respuesta_Secuencia = this.Respuesta_Secuencia;
            this.OnEntityAction(new CodeFluent.Runtime.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, registroPreguntasCata));
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
		#region Static SQL Methods

		internal static string GetFieldAliasFromFieldNameSqlMapping(string alias)
		{
			alias = alias.Replace("[", string.Empty).Replace("]", string.Empty);
			switch (alias.ToLower())
			{
				case "pregunta_descripcion": return "pregunta_descripcion";
				case "pregunta_secuencia": return "pregunta_secuencia";
				case "registro_estado": return "registro_estado";
				case "registro_fecha": return "registro_fecha";
				case "registro_usuario": return "registro_usuario";
				case "respuesta_secuencia": return "respuesta_secuencia";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldAliasSqlMapping(string alias)
		{
			switch (alias.ToLower())
			{
				case "pregunta_descripcion": return "Registro_Preguntas_Cata";
				case "pregunta_secuencia": return "Registro_Preguntas_Cata";
				case "registro_estado": return "Registro_Preguntas_Cata";
				case "registro_fecha": return "Registro_Preguntas_Cata";
				case "registro_usuario": return "Registro_Preguntas_Cata";
				case "respuesta_secuencia": return "Registro_Preguntas_Cata";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetTableFromFieldNameSqlMapping(string field)
		{
			switch (field.ToLower())
			{
				case "pregunta_descripcion": return "Registro_Preguntas_Cata";
				case "pregunta_secuencia": return "Registro_Preguntas_Cata";
				case "registro_estado": return "Registro_Preguntas_Cata";
				case "registro_fecha": return "Registro_Preguntas_Cata";
				case "registro_usuario": return "Registro_Preguntas_Cata";
				case "respuesta_secuencia": return "Registro_Preguntas_Cata";
				default: throw new Exception("The select clause is not valid.");
			}
		}

		internal static string GetRemappedLinqSql(string sql, string parentAlias, LinqSQLFromClauseCollection childTables)
		{
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[pregunta_descripcion\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[pregunta_descripcion]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[pregunta_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[pregunta_secuencia]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_estado\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[registro_estado]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_fecha\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[registro_fecha]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[registro_usuario\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[registro_usuario]", RegexOptions.IgnoreCase);
			sql = System.Text.RegularExpressions.Regex.Replace(sql, "\\[" + parentAlias + "\\]\\.\\[respuesta_secuencia\\]", "[" + childTables.GetBaseAliasTable(parentAlias, "Registro_Preguntas_Cata") + "].[respuesta_secuencia]", RegexOptions.IgnoreCase);
			return sql;
		}

		#endregion


	}

}

