using System;
namespace nHydrate.Dsl.Editor
    {
	public enum ImageLibraryIndex
	{
		CodeFluentFolder = 1,
		OpenCodeFluentFolder,
		ReferenceFolder,
		Reference,
		UnresolvedReference,
		Folder = 7,
		OpenFolder,
		ExcludedFolder,
		OpenExcludedFolder,
		ExcludedFile,
		MissingFile = 13,
		CodeFluentNamespacesView,
		CodeFluentSolarView,
		CodeFluentEmptyView,
		CodeFluentModel,
		CodeFluentGoToXml,
		CodeFluentGrid,
		CodeFluentModelGrid,
		CodeFluentProducer,
		CodeFluentPattern,
		CodeFluentPropertyRule,
		CodeFluentEntityRule,
		CodeFluentSaveSurface,
		CodeFluentNewSurface,
		CodeFluentStylesheet,
		CodeFluentCollection,
		CodeFluentRule = 21,
		CodeFluentResource = 31,
		CodeFluentMembership,
		CodeFluentRenderer = 34,
		CodeFluentApplication,
		XWorld,
		CodeFluentSchema,
		CodeFluentTreeView = 37,
		CodeFluentView,
		CodeFluentAdd,
		CodeFluentRename,
		CodeFluentConstraint = 61,
		CodeFluentModelSearch = 42,
		MissingReference,
		CodeFluentStandardType,
		CodeFluentConceptAction,
		CodeFluentPackage,
		CodeFluentStore,
		CodeFluentApplication2,
		CodeFluentImport,
		License = 51,
		CodeFluentSurface,
		CodeFluentProject,
		CodeFluentSave,
		CodeFluentCategory,
		CodeFluentBody,
		CodeFluentRawMethod,
		CodeFluentSnippet,
		CodeFluentViewProperty,
		CodeFluentInstance,
		CodeFluentInstanceValue,
		CodeFluentEntity,
		CodeFluentEnumeration,
		CodeFluentNamespace,
		CodeFluentPart,
		CodeFluentProjectPart,
		CodeFluentDefaultPart,
		CodeFluentDerivedEntity,
		CodeFluentLightWeightEntity,
		CodeFluentExistingEntity,
		CodeFluentMethod,
		CodeFluentProperty,
		CodeFluentEnumerationValue,
		CodeFluentUserType,
		CodeFluentCut,
		CodeFluentCopy,
		CodeFluentPaste,
		CodeFluentDelete,
		CodeFluentSearch,
		CodeFluentSelector = 79,
		CodeFluentBuild,
		CodeFluentPasteSpecial,
		CodeFluentCopyAsXml,
		CodeFluentRemoveSurface,
		CodeFluentRemoveFromSurface,
		CodeFluentParameter,
		CodeFluentProducers,
		CodeFluentSurfaces,
		CodeFluentParts,
		CodeFluentModels,
		CodeFluentPatterns,
		CodeFluentStruct,
		CodeFluentSpecificProcedure,
		CodeFluentCfqlProcedure,
		CodeFluentTables,
		CodeFluentColumn,
		CodeFluentKey,
		CodeFluentDbEngine,
		CodeFluentTable,
		CodeFluentForms,
		CodeFluentCulture,
		CodeFluentUIControlDefinition,
		CodeFluentUIForm,
		CodeFluentViews = 104,
		CodeFluentPersistentView,
		CodeFluentSetting = 107,
		CodeFluentEnumerationFlags,
		CodeFluentAttribute,
		CodeFluentAttributeArgument,
		CodeFluentUITab,
		CodeFluentUIColumn,
		CodeFluentUIField,
		CodeFluentUIControl,
		CodeFluentUIWindow,
		CodeFluentMessage,
		CodeFluentGlobalMessage,
		CodeFluentDisabledProducer,
		CodeFluentSubProducer,
		CodeFluentDisabledSubProducer,
		CodeFluentInvalidProducer,
		CodeFluentInvalidSubProducer,
		CodeFluentStores,
		CodeFluentUserTypes,
		CodeFluentExistingEnumeration,
		CodeFluentPrimaryKey,
		CodeFluentForeignKey,
		CodeFluentPropertyEntity,
		CodeFluentPropertyKey,
		CodeFluentSurfaceParts,
		CodeFluentSurfacePart,
		CodeFluentNewPattern,
		CodeFluentReferencedPattern,
		CodeFluentNewTab,
		CodeFluentPropertyBlob,
		CodeFluentPropertyEnum,
		CodeFluentPropertyCollection,
		CodeFluentAutoLightweightView,
		CodeFluentDescriptor,
		NavPath,
		CodeFluentPropertyComputed,
		CodeFluentSystemPattern,
		Checkbox,
		Checked,
		CodeFluentCompiledPattern,
		Import,
		StarterWizard,
		CodeFluentMetroStore,
		CodeFluentMetroUserType,
		CodeFluentMetroPattern,
		CodeFluentMetroEntityFormat,
		CodeFluentMetroPropertyFormat,
		CodeFluentMetroDelete,
		CodeFluentMetroCopy,
		CodeFluentMetroCut,
		CodeFluentMetroPaste,
		CodeFluentMetroCopyAsXml,
		MetroReference,
		CodeFluentMetroPart
	}
}
