//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:11 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System; 
using System.Collections.Generic; 
using System.Linq; 
using System.Web.Mvc; 
using System.Web; 
using System.Web.UI; 
using CodeFluent.Runtime; 
using OSIS.PEPPAM.Mvc.Models; 
using OSIS.PEPPAM.Mvc.Extensions.Controllers; 
using OSIS.PEPPAM.Mvc.Models.Shared; 
using OSIS.PEPPAM.Mvc.Extensions.ActionResults; 
using OSIS.PEPPAM.Mvc.Extensions.Controllers; 
using OSIS.PEPPAM.Mvc.Extensions.Helpers; 
using OSIS.PEPPAM.Mvc.Models.Shared; 
using OSIS.PEPPAM.Mvc.Models; 
using OSIS.PEPPAM.Mvc.UI; 
 
namespace OSIS.PEPPAM.Mvc.Controllers 
{ 
    public partial class Registro_Respuestas_CataController : Registro_Respuestas_CataControllerBase 
    { 

    } 
 
	public partial class Registro_Respuestas_CataControllerBase : BaseController 
	{ 
		#region Members 
 

 
        #endregion 
 
        #region Constructors 
 

 
        #endregion 
 
		#region Index 
 

public virtual ActionResult Index()
{
    var model = new Registro_Respuestas_CataModel();

    ViewBag.PageIndex = this.GetPageIndex();
    ViewBag.PageSize = this.GetPageSize();
    ViewBag.SearchValue = this.GetSearchValue();

    return View(model);
}


[HttpPost]
public virtual ActionResult Load(GridRequestViewModel gridRequest)
{
    OrderByArgumentCollection orderByArguments = new OrderByArgumentCollection();
    orderByArguments.Add("[" + gridRequest.SortColumnName + "]", gridRequest.SortDirection);

    PageOptions pageOptions = new PageOptions();
    pageOptions.OrderByArguments = orderByArguments;

    var totalCount = 0;

    var allregistroRespuestasCata = Registro_Respuestas_CataModel.PageLoadAllPaging(1 + gridRequest.RowStartIndex/gridRequest.RowCount,
        gridRequest.RowCount, gridRequest.Search, pageOptions, out totalCount);

    var displayRecords = allregistroRespuestasCata.Count;
    var totalRecords = totalCount;

    var dateFormat = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "en"
        ? "MM/dd/yyyy"
        : "dd/MM/yyyy";
    System.Globalization.DateTimeFormatInfo dtfi =
        System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat;
    dtfi.DateSeparator = "/";

    return Json(new
    {
        iTotalDisplayRecords = displayRecords,
        iTotalRecords = totalRecords,
        sEcho = gridRequest.GridCustomData,
        aaData =
            allregistroRespuestasCata.Select(
                d =>
                    new
                    {
d.Respuesta_Secuencia,d.Respuesta_Descripcion,d.Registro_Estado,Registro_Fecha = d.Registro_Fecha.ToString(dateFormat, dtfi),d.Registro_Usuario,Respuesta_Categoria_Secuencia = d.RegistroRespuetaCategoriasCata != null ? d.RegistroRespuetaCategoriasCata.EntityDisplayName : string.Empty
                    })
    });

}

public virtual ActionResult Report()
{
    var totalCount = 0;
    var allregistroRespuestasCata = Registro_Respuestas_CataModel.LoadAllPaging(this.GetSearchValue(), out totalCount);

    var dateFormat = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "en"
        ? "MM/dd/yyyy"
        : "dd/MM/yyyy";
    System.Globalization.DateTimeFormatInfo dtfi =
        System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat;
    dtfi.DateSeparator = "/";
    return new CsvReportResult("Registro_Respuestas_Cata",
        allregistroRespuestasCata.Select(
            d =>
                new
                {
d.Respuesta_Secuencia,d.Respuesta_Descripcion,d.Registro_Estado,Registro_Fecha = d.Registro_Fecha.ToString(dateFormat, dtfi),d.Registro_Usuario,Respuesta_Categoria_Secuencia = d.RegistroRespuetaCategoriasCata != null ? d.RegistroRespuetaCategoriasCata.EntityDisplayName : string.Empty
                }));
}


[HttpPost]
public virtual ActionResult Delete( string entityKey)

{
    try
    {
        var deleteModel  = Registro_Respuestas_CataModel.LoadByEntityKey(entityKey);
       if (deleteModel.Delete())
       {
          return Json(new { cssMainClass = "success", title = Messages.GetOrSetMensaje("MENSAJE_OPERACION_REALIZDA_SASTIFACTORIAMENTE_HEADER"), body = Messages.GetOrSetMensaje("MENSAJE_NOTIFICACION_REGISTRO_BORRADO") }, JsonRequestBehavior.AllowGet);
       }
       else
       {
          return Json(new { cssMainClass = "warning", title = Messages.GetOrSetMensaje("MENSAJE_PRECAUSION_HEADER"), body = Messages.GetOrSetMensaje("MENSAJE_NOTIFICACION_REGISTRO_NO_BORRADO") }, JsonRequestBehavior.AllowGet);
       }
    }
    catch (Exception ex)
    {
          return Json(new { cssMainClass = "success", title = Messages.GetOrSetMensaje("MENSAJE_PRECAUSION_HEADER"), body = Messages.GetOrSetMensaje("MENSAJE_NOTIFICACION_REGISTRO_BORRADO") }, JsonRequestBehavior.AllowGet);
    }
    return Content(string.Empty);
}
		 
 
		#endregion 
 
		#region Create 
 

		// ******************************************* 
        // URL: /Registro_Respuestas_Cata/Create 
        // ******************************************* 

public virtual ActionResult Create()
{
    var registroRespuestasCata = new Registro_Respuestas_CataModel();
    ViewBag.IsNew = true;
    registroRespuestasCata.Registro_Estado = "A";

    return View(registroRespuestasCata);
}

//
// POST: /Usuarios/Create
[HttpPost]
public virtual ActionResult Create(Registro_Respuestas_CataModel registroRespuestasCata)
{
    if (ModelState.IsValid)
    {

        //Campos Auditorias
        registroRespuestasCata.Registro_Fecha = DateTime.Now;
        registroRespuestasCata.Registro_Usuario = User.Identity.Name;
                
        var result = registroRespuestasCata.Save();

        if (result)
        {
            return RedirectToAction("Edit", new { 
respuesta_Secuencia = registroRespuestasCata.Respuesta_Secuencia});
        }

    }

    ViewBag.IsNew = true;
    return View(registroRespuestasCata);
            
}

		 
 
		#endregion 
 
		#region Edit 
 

		// ******************************************* 
        // URL: /Registro_Respuestas_Cata/Edit/id 
        // ******************************************* 

public virtual ActionResult Edit(int respuesta_Secuencia)
{

    var registroRespuestasCata = Registro_Respuestas_CataModel.LoadByEntityKey(respuesta_Secuencia.ToString());

    ViewBag.IsNew = false;
            
    return View(registroRespuestasCata);
}

[HttpPost]
public virtual ActionResult Edit(Registro_Respuestas_CataModel registroRespuestasCata)
{
           
        if (ModelState.IsValid)
        {
        //Campos Auditorias
        registroRespuestasCata.Registro_Fecha = DateTime.Now;
        registroRespuestasCata.Registro_Usuario = User.Identity.Name;
                

            var result = registroRespuestasCata.Save();

            if (result)
            {
                return RedirectToAction("Index");
            }
        }

        ViewBag.IsNew = false;
        return View(registroRespuestasCata);
}

public virtual ActionResult LoadRegistroPreguntasCata(GridRequestViewModel gridRequest,int respuesta_Secuencia){
    var registro_Preguntas_Cata = Registro_Respuestas_CataModel.LoadByEntityKey(respuesta_Secuencia.ToString());

    int count = registro_Preguntas_Cata.RegistroPreguntasCata.Count;

    var dateFormat = System.Globalization.CultureInfo.CurrentCulture.TwoLetterISOLanguageName == "en" ? "MM/dd/yyyy" : "dd/MM/yyyy";
    System.Globalization.DateTimeFormatInfo dtfi = System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat;
    dtfi.DateSeparator = "/";

    return Json(new
    {
        iTotalDisplayRecords = count,
        iTotalRecords = count,
        sEcho = gridRequest.GridCustomData,
        aaData = registro_Preguntas_Cata.RegistroPreguntasCata.Skip(gridRequest.RowStartIndex)
                        .Take(gridRequest.RowCount)
                        .Select(d => new { 
d.Pregunta_Secuencia,d.Pregunta_Descripcion,d.Registro_Estado,Registro_Fecha = d.Registro_Fecha.ToString(dateFormat, dtfi),d.Registro_Usuario,Respuesta_Secuencia = d.RegistroRespuestasCata != null ? d.RegistroRespuestasCata.EntityDisplayName : string.Empty
    })
 });

}

public virtual ActionResult AddRegistroPreguntasCata(int respuesta_Secuencia){
    var registro_Respuestas_Cata = Registro_Respuestas_CataModel.LoadByEntityKey(respuesta_Secuencia.ToString());

    var registro_Preguntas_Cata = new Registro_Preguntas_CataModel();

 registro_Preguntas_Cata.Respuesta_Secuencia =registro_Respuestas_Cata.Respuesta_Secuencia;            

    ViewBag.MasterProperty = "Registro_Respuestas_Cata_Registro_Preguntas_Cata";

    //relations

    ViewBag.Name = "AddRegistro_Preguntas_Cata";
    ViewBag.IsNew = true;
    registro_Preguntas_Cata.Registro_Estado = "A";

    return PartialView("~/Views/Registro_Preguntas_Cata/PopUp.cshtml", registro_Preguntas_Cata);
}

[HttpPost]
public virtual ActionResult AddRegistroPreguntasCata(Registro_Preguntas_CataModel registro_Preguntas_Cata)
{
    if (ModelState.IsValid)
    {

        //Campos Auditorias
        registro_Preguntas_Cata.Registro_Fecha = DateTime.Now;
        registro_Preguntas_Cata.Registro_Usuario = User.Identity.Name;

        registro_Preguntas_Cata.Save();
                
        return new HttpStatusCodeResult(200);
    }
    return new HttpStatusCodeResult(500);
}

//Columna por las cuales estan relacionadas
public virtual ActionResult EditRegistroPreguntasCata(int respuesta_Secuencia_parent, int pregunta_Secuencia_child )
{
    var registro_Preguntas_Cata =  Registro_Preguntas_CataModel.LoadByEntityKey(pregunta_Secuencia_child.ToString());
            
    ViewBag.MasterProperty = "Registro_Respuestas_Cata_Registro_Preguntas_Cata";
    ViewBag.Name = "EditRegistro_Preguntas_Cata";
    ViewBag.IsNew = false;

    return PartialView("~/Views/Registro_Preguntas_Cata/PopUp.cshtml", registro_Preguntas_Cata);
}

[HttpPost]
public virtual ActionResult EditRegistroPreguntasCata(Registro_Preguntas_CataModel registro_Preguntas_Cata)
{
    if (ModelState.IsValid)
    {
        //Campos Auditorias
        registro_Preguntas_Cata.Registro_Fecha = DateTime.Now;
        registro_Preguntas_Cata.Registro_Usuario = User.Identity.Name;
        registro_Preguntas_Cata.Save();

        return new HttpStatusCodeResult(200);
    }
    return new HttpStatusCodeResult(500);
}

[HttpPost]
public virtual ActionResult DeleteRegistroPreguntasCata(int respuesta_Secuencia_parent, int pregunta_Secuencia_child ){
    var registro_Preguntas_Cata = Registro_Preguntas_CataModel.LoadByEntityKey(pregunta_Secuencia_child.ToString());
       if (registro_Preguntas_Cata.Delete())
       {
          return Json(new { cssMainClass = "success", title = Messages.GetOrSetMensaje("MENSAJE_OPERACION_REALIZDA_SASTIFACTORIAMENTE_HEADER"), body = Messages.GetOrSetMensaje("MENSAJE_NOTIFICACION_REGISTRO_BORRADO") }, JsonRequestBehavior.AllowGet);
       }
       else
       {
          return Json(new { cssMainClass = "warning", title = Messages.GetOrSetMensaje("MENSAJE_PRECAUSION_HEADER"), body = Messages.GetOrSetMensaje("MENSAJE_NOTIFICACION_REGISTRO_NO_BORRADO") }, JsonRequestBehavior.AllowGet);
       }

}

public virtual ActionResult ReportRegistroPreguntasCata(int respuesta_Secuencia){
    var registro_Preguntas_Cata = Registro_Respuestas_CataModel.LoadByEntityKey(respuesta_Secuencia.ToString());            
    return new CsvReportResult("Registro_Preguntas_Cata", registro_Preguntas_Cata.RegistroPreguntasCata);
}

		 
 
		#endregion 
 
		#region Details 
 

		 
 
		#endregion 

	} 
} 


