namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Shared", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to $AppName$.
        /// </summary>
        internal static string AppName
        {
            get
            {
                return ResourceManager.GetString("$AppName$", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string Clean
        {
            get
            {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create
        {
            get
            {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        internal static string CreateViewTitle
        {
            get
            {
                return ResourceManager.GetString("CreateViewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details
        {
            get
            {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details of  {0}.
        /// </summary>
        internal static string DetailsViewTitle
        {
            get
            {
                return ResourceManager.GetString("DetailsViewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string DoSearch
        {
            get
            {
                return ResourceManager.GetString("DoSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download
        {
            get
            {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editing {0}.
        /// </summary>
        internal static string EditViewTitle
        {
            get
            {
                return ResourceManager.GetString("EditViewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string ErrorPageText
        {
            get
            {
                return ResourceManager.GetString("ErrorPageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file could not be found.
        /// </summary>
        internal static string FileNotFound
        {
            get
            {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total elements: .
        /// </summary>
        internal static string GridTotal
        {
            get
            {
                return ResourceManager.GetString("GridTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home
        {
            get
            {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file could not be uploaded.
        /// </summary>
        internal static string ImpossibleLoadFile
        {
            get
            {
                return ResourceManager.GetString("ImpossibleLoadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List of {0}.
        /// </summary>
        internal static string IndexViewTitle
        {
            get
            {
                return ResourceManager.GetString("IndexViewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information was saved.
        /// </summary>
        internal static string InformationWasSaved
        {
            get
            {
                return ResourceManager.GetString("InformationWasSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        internal static string LogOff
        {
            get
            {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NotSet
        {
            get
            {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove
        {
            get
            {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report
        {
            get
            {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string RequiredField
        {
            get
            {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the elements.
        /// </summary>
        internal static string SelectElements
        {
            get
            {
                return ResourceManager.GetString("SelectElements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown document.
        /// </summary>
        internal static string UnknownDocument
        {
            get
            {
                return ResourceManager.GetString("UnknownDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View more....
        /// </summary>
        internal static string ViewMore
        {
            get
            {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Language
        /// </summary>
        internal static string CurrentLanguage
        {
            get
            {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There were errors
        /// </summary>
        internal static string ThereWereErrors
        {
            get
            {
                return ResourceManager.GetString("ThereWereErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected items
        /// </summary>
        internal static string SelectedItems
        {
            get
            {
                return ResourceManager.GetString("SelectedItems", resourceCulture);
            }
        }


    }
}
