//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Web; 
using System.Linq; 
using System.Collections.Generic; 
using CodeFluent.Runtime; 
using CodeFluent.Runtime.Utilities; 
using System.ComponentModel.DataAnnotations; 
using FluentValidation; 
using FluentValidation.Attributes; 
using OSIS.PEPPAM.Mvc.Models; 

namespace OSIS.PEPPAM.Mvc.Models 
{ 
	public partial class Persona_Roles_TransModel
	{

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Persona_Roles_Trans","Persona_Secuencia")]
		public int Persona_Secuencia { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Persona_Roles_Trans","Role_Numero")]
		public int Role_Numero { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Persona_Roles_Trans","Registro_Estado")]
		public String Registro_Estado { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Persona_Roles_Trans","Registro_Fecha")]
		public DateTime Registro_Fecha { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Persona_Roles_Trans","Registro_Usuario")]
		public String Registro_Usuario { get; set; } 

		#region Navigation Properties

        public OSIS.PEPPAM.Mvc.Models.Personas_MasterModel _personas_Master;
		/// <summary>
		/// The navigation definition for walking [Persona_Roles_Trans]->[Personas_Master]
		/// Relationship Links: 
		/// [Personas_Master.Persona_Secuencia = Persona_Roles_Trans.Persona_Secuencia] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.Mvc.Models.Personas_MasterModel PersonasMaster
		{
			get
			{
                if ((this._personas_Master == null))
                {
                    this._personas_Master = OSIS.PEPPAM.Mvc.Models.Personas_MasterModel.Load(Persona_Secuencia);
                }
                return this._personas_Master;
			}
		}

     private List<OSIS.PEPPAM.Mvc.Models.Personas_MasterModel> _personas_MasterList;
		public virtual List<OSIS.PEPPAM.Mvc.Models.Personas_MasterModel> PersonasMasterList
		{
			get
			{
                if ((this._personas_MasterList == null))
                {
                    this._personas_MasterList = OSIS.PEPPAM.Mvc.Models.Personas_MasterModel.LoadAll();
                }
                return this._personas_MasterList;
			}
		}

        public OSIS.PEPPAM.Mvc.Models.Roles_CataModel _roles_Cata;
		/// <summary>
		/// The navigation definition for walking [Persona_Roles_Trans]->[Roles_Cata]
		/// Relationship Links: 
		/// [Roles_Cata.Role_Numero = Persona_Roles_Trans.Role_Numero] (Required)
		/// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
		public virtual OSIS.PEPPAM.Mvc.Models.Roles_CataModel RolesCata
		{
			get
			{
                if ((this._roles_Cata == null))
                {
                    this._roles_Cata = OSIS.PEPPAM.Mvc.Models.Roles_CataModel.Load(Role_Numero);
                }
                return this._roles_Cata;
			}
		}

     private List<OSIS.PEPPAM.Mvc.Models.Roles_CataModel> _roles_CataList;
		public virtual List<OSIS.PEPPAM.Mvc.Models.Roles_CataModel> RolesCataList
		{
			get
			{
                if ((this._roles_CataList == null))
                {
                    this._roles_CataList = OSIS.PEPPAM.Mvc.Models.Roles_CataModel.LoadAll();
                }
                return this._roles_CataList;
			}
		}

		#endregion

        public virtual string EntityKey
        {
            get
            {
                object[] keys = new object[] {
                        this.Persona_Secuencia,
                        this.Role_Numero
                 };
                string v = CodeFluentPersistence.BuildEntityKey(keys);
                return v;
            }
            set
            {
                System.Type[] types = new System.Type[] {
                        typeof(int),
                        typeof(int)
                        };
                object[] defaultValues = new object[] {
                        -1,
                        -1
                        };
                object[] v1 = CodeFluentPersistence.ParseEntityKey(value, types, defaultValues);
                this. Persona_Secuencia = ((int)(v1[0]));
                this. Role_Numero = ((int)(v1[1]));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Registro_Estado.ToString();
            }
        }
        

        public Persona_Roles_TransModel()
        {
            this.Persona_Secuencia = -1;
            this.Role_Numero = -1;
            this.Registro_Estado = "A";
            this.Registro_Fecha = DateTime.Now;
            this.Registro_Usuario = HttpContext.Current != null ? HttpContext.Current.User.Identity.Name : "";
            Persona_Roles_TransPartial();
        }

            partial void Persona_Roles_TransPartial();

        public virtual bool Equals(OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans)
        {
            if ((personaRolesTrans == null))
            {
                return false;
            }

            if (
                    (this.Persona_Secuencia == -1)
                    ||
                    (this.Role_Numero == -1)
            )
            {
                return base.Equals(personaRolesTrans);
            }

 return ((
                    (this.Persona_Secuencia.Equals(personaRolesTrans.Persona_Secuencia))
                    &&
                    (this.Role_Numero.Equals(personaRolesTrans.Role_Numero))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans = null;
			 personaRolesTrans = obj as OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel;
            return this.Equals( personaRolesTrans);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        public virtual int CompareTo(OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans)
        {
            if ((personaRolesTrans == null))
            {
                throw new System.ArgumentNullException("personaRolesTrans");
            }
            int localCompareTo = this.Persona_Secuencia.CompareTo(personaRolesTrans.Persona_Secuencia);
            return localCompareTo;
        }

        public static OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel Load(int persona_Secuencia,int role_Numero)
        {
            var _personaRolesTransDb = OSIS.PEPPAM.BOM.Persona_Roles_Trans.Load(persona_Secuencia,role_Numero);
	        if (_personaRolesTransDb == null)
	        {
                return null;
	        }

	        var _personaRolesTrans = new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
            {
                Persona_Secuencia = _personaRolesTransDb.Persona_Secuencia,
                Role_Numero = _personaRolesTransDb.Role_Numero,
                Registro_Estado = _personaRolesTransDb.Registro_Estado,
                Registro_Fecha = _personaRolesTransDb.Registro_Fecha,
                Registro_Usuario = _personaRolesTransDb.Registro_Usuario,

            };

	        return _personaRolesTrans;
       }

     public virtual bool Save()
	        {
             var _personaRolesTransDb = new OSIS.PEPPAM.BOM.Persona_Roles_Trans()
	            {
                Persona_Secuencia = this.Persona_Secuencia,
                Role_Numero = this.Role_Numero,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            var result  = _personaRolesTransDb.Save();
             //TODO: Puede ser que solo sean los Identity y no todo los primary keys
             this.Persona_Secuencia = _personaRolesTransDb.Persona_Secuencia;
             //TODO: Puede ser que solo sean los Identity y no todo los primary keys
             this.Role_Numero = _personaRolesTransDb.Role_Numero;

             return result;

	        }

        public static bool Save(OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans)
        {
            if ((personaRolesTrans == null))
            {
                return false;
            }
            bool ret = personaRolesTrans.Save();
            return ret;
        }

        public static bool Insert(OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans)
        {
            bool ret = OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel.Save(personaRolesTrans);
            return ret;
        }

        public static void SaveAll(List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> personaRolesTrans)
        {
            int index;
            for (index = (personaRolesTrans.Count - 1); (index >= 0); index = (index - 1))
            {
                OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel _personaRolesTrans = personaRolesTrans[index];
                _personaRolesTrans.Save();
            }
        }

        public static bool Delete(OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans)
        {
            if ((personaRolesTrans == null))
            {
                return false;
            }
            bool ret = personaRolesTrans.Delete();
            return ret;
        }

         public virtual bool Delete()
	        {
             var _personaRolesTransDb = new OSIS.PEPPAM.BOM.Persona_Roles_Trans()
	            {
                Persona_Secuencia = this.Persona_Secuencia,
                Role_Numero = this.Role_Numero,

	            };

	            return _personaRolesTransDb.Delete();

	        }

        public static bool Delete(int persona_Secuencia,int role_Numero)
        {
            if ((persona_Secuencia == default(int)))
            {
                return false;
            }
            if ((role_Numero == default(int)))
            {
                return false;
            }
             var _personaRolesTransDb = OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel.Load(persona_Secuencia,role_Numero);
            return _personaRolesTransDb.Delete();
        }

        public string Trace()
	        {
             var _personaRolesTransDb = new OSIS.PEPPAM.BOM.Persona_Roles_Trans()
	            {
                Persona_Secuencia = this.Persona_Secuencia,
                Role_Numero = this.Role_Numero,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            return _personaRolesTransDb.Trace();

	        }

        public static OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel personaRolesTrans;
            System.Type[] types = new System.Type[] {
                    typeof(int),                    typeof(int)                    };
            object[] defaultValues = new object[] {
                    -1,                    -1                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    int var0;            var0 = ((int)(v[0]));
                    int var1;            var1 = ((int)(v[1]));
            personaRolesTrans = OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel.Load( var0, var1);
            return personaRolesTrans;
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
        public  OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel Clone(bool deep)
        {
             OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel  personaRolesTrans = new  OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel();
            this.CopyTo(personaRolesTrans , deep);
            return personaRolesTrans ;
        }

        public OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel Clone()
        {
            OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel localClone = this.Clone(true);
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Persona_Secuencia") == true))
            {
                this.Persona_Secuencia = ((int)(ConvertUtilities.ChangeType(dict["Persona_Secuencia"], typeof(int), -1)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Role_Numero") == true))
            {
                this.Role_Numero = ((int)(ConvertUtilities.ChangeType(dict["Role_Numero"], typeof(int), -1)));
            }
        }

        public virtual void CopyTo( OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel  personaRolesTrans, bool deep)
        {
            if ((personaRolesTrans == null))
            {
                throw new System.ArgumentNullException("personaRolesTrans");
            }
            personaRolesTrans.Persona_Secuencia = this.Persona_Secuencia;
            personaRolesTrans.Registro_Estado = this.Registro_Estado;
            personaRolesTrans.Registro_Fecha = this.Registro_Fecha;
            personaRolesTrans.Registro_Usuario = this.Registro_Usuario;
            personaRolesTrans.Role_Numero = this.Role_Numero;
        }

	public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadAll(int pageIndex, int pageSize,
	        CodeFluent.Runtime.PageOptions pageOptions)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadAll(pageIndex, pageSize, pageOptions);

	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _personaRolesTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
	        {
                Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                Role_Numero = _personaRolesTrans.Role_Numero,
                Registro_Estado = _personaRolesTrans.Registro_Estado,
                Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                Registro_Usuario = _personaRolesTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> LoadAll()
        {
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadAll(int.MinValue, int.MaxValue, null);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                Role_Numero = _personaRolesTrans.Role_Numero,
                Registro_Estado = _personaRolesTrans.Registro_Estado,
                Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                Registro_Usuario = _personaRolesTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> LoadByPersonasMaster(OSIS.PEPPAM.Mvc.Models.Personas_MasterModel personas_Master)
        {

            var _Personas_Master = new OSIS.PEPPAM.BOM.Personas_Master()
            {
                Persona_Secuencia = personas_Master.Persona_Secuencia,
                Congregacion_Secuencia = personas_Master.Congregacion_Secuencia,
                Persona_Congregacion = personas_Master.Persona_Congregacion,
                Persona_Tipo_Secuencia = personas_Master.Persona_Tipo_Secuencia,
                Persona_Nombres = personas_Master.Persona_Nombres,
                Persona_Apellidos = personas_Master.Persona_Apellidos,
                Persona_Conyuge_Apellido = personas_Master.Persona_Conyuge_Apellido,
                Persona_Sexo = personas_Master.Persona_Sexo,
                Persona_Correo = personas_Master.Persona_Correo,
                Persona_Clave = personas_Master.Persona_Clave,
                Persona_Verificacion_Numero = personas_Master.Persona_Verificacion_Numero,
                Persona_Estado_Secuencia = personas_Master.Persona_Estado_Secuencia,
                Registro_Estado = personas_Master.Registro_Estado,
                Registro_Fecha = personas_Master.Registro_Fecha,
                Registro_Usuario = personas_Master.Registro_Usuario,
            };


            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.LoadByPersonasMaster(_Personas_Master);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


    [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadByPersonasMaster(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.Mvc.Models.Personas_MasterModel personas_Master)
        {
            var _personas_Master = new OSIS.PEPPAM.BOM.Personas_Master()
            {
                Persona_Secuencia = personas_Master.Persona_Secuencia,
                Congregacion_Secuencia = personas_Master.Congregacion_Secuencia,
                Persona_Congregacion = personas_Master.Persona_Congregacion,
                Persona_Tipo_Secuencia = personas_Master.Persona_Tipo_Secuencia,
                Persona_Nombres = personas_Master.Persona_Nombres,
                Persona_Apellidos = personas_Master.Persona_Apellidos,
                Persona_Conyuge_Apellido = personas_Master.Persona_Conyuge_Apellido,
                Persona_Sexo = personas_Master.Persona_Sexo,
                Persona_Correo = personas_Master.Persona_Correo,
                Persona_Clave = personas_Master.Persona_Clave,
                Persona_Verificacion_Numero = personas_Master.Persona_Verificacion_Numero,
                Persona_Estado_Secuencia = personas_Master.Persona_Estado_Secuencia,
                Registro_Estado = personas_Master.Registro_Estado,
                Registro_Fecha = personas_Master.Registro_Fecha,
                Registro_Usuario = personas_Master.Registro_Usuario,
            };
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadByPersonasMaster(int.MinValue, int.MaxValue, null, _personas_Master);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadByPersonasMaster(int pageIndex, int pageSize,int persona_Secuencia)
        {
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadByPersonasMaster(int.MinValue, int.MaxValue,
persona_Secuencia);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }
        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> LoadByRolesCata(OSIS.PEPPAM.Mvc.Models.Roles_CataModel roles_Cata)
        {

            var _Roles_Cata = new OSIS.PEPPAM.BOM.Roles_Cata()
            {
                Role_Numero = roles_Cata.Role_Numero,
                Role_Nivel_Numero = roles_Cata.Role_Nivel_Numero,
                Role_Nombre = roles_Cata.Role_Nombre,
                Role_Descripcion = roles_Cata.Role_Descripcion,
                Registro_Estado = roles_Cata.Registro_Estado,
                Registro_Fecha = roles_Cata.Registro_Fecha,
                Registro_Usuario = roles_Cata.Registro_Usuario,
            };


            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.LoadByRolesCata(_Roles_Cata);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


    [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadByRolesCata(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, OSIS.PEPPAM.Mvc.Models.Roles_CataModel roles_Cata)
        {
            var _roles_Cata = new OSIS.PEPPAM.BOM.Roles_Cata()
            {
                Role_Numero = roles_Cata.Role_Numero,
                Role_Nivel_Numero = roles_Cata.Role_Nivel_Numero,
                Role_Nombre = roles_Cata.Role_Nombre,
                Role_Descripcion = roles_Cata.Role_Descripcion,
                Registro_Estado = roles_Cata.Registro_Estado,
                Registro_Fecha = roles_Cata.Registro_Fecha,
                Registro_Usuario = roles_Cata.Registro_Usuario,
            };
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadByRolesCata(int.MinValue, int.MaxValue, null, _roles_Cata);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadByRolesCata(int pageIndex, int pageSize,int role_Numero)
        {
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadByRolesCata(int.MinValue, int.MaxValue,
role_Numero);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                        Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                        Role_Numero = _personaRolesTrans.Role_Numero,
                        Registro_Estado = _personaRolesTrans.Registro_Estado,
                        Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                        Registro_Usuario = _personaRolesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }
	public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> PageLoadAllPaging(int pageIndex, int pageSize, string searchString,
	        CodeFluent.Runtime.PageOptions pageOptions, out int totalCount)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadAllPaging(pageIndex, pageSize, searchString, pageOptions);

	        totalCount = pageLoadAll.TotalRowCount;
	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _personaRolesTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
	        {
                Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                Role_Numero = _personaRolesTrans.Role_Numero,
                Registro_Estado = _personaRolesTrans.Registro_Estado,
                Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                Registro_Usuario = _personaRolesTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel> LoadAllPaging(string searchString, out int totalCount)
        {
            OSIS.PEPPAM.BOM.Persona_Roles_TransCollection ret = OSIS.PEPPAM.BOM.Persona_Roles_TransCollection.PageLoadAllPaging(1, 1000000,searchString, null);

	            totalCount = ret.TotalRowCount;
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel>();
            }

            var result = ret.Select(
                _personaRolesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Persona_Roles_TransModel()
                    {
                Persona_Secuencia = _personaRolesTrans.Persona_Secuencia,
                Role_Numero = _personaRolesTrans.Role_Numero,
                Registro_Estado = _personaRolesTrans.Registro_Estado,
                Registro_Fecha = _personaRolesTrans.Registro_Fecha,
                Registro_Usuario = _personaRolesTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

	} 
} 


