//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
  using System.Collections.Generic;
  using System.Linq;
 using System.Runtime.Serialization;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
namespace OSIS.PEPPAM.Mvc.Models
{
    
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    public partial class Proc_Turnos_DisponiblesBase
    {


        
        public Proc_Turnos_DisponiblesBase()
        {
        }

		#region Primitive Properties

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Cantidad_Dias
		{
			get { return _cantidad_Dias; }
			set
			{
				_cantidad_Dias = value;
			}
		}
		protected int? _cantidad_Dias = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Cantidad_Ocupado
		{
			get { return _cantidad_Ocupado; }
			set
			{
				_cantidad_Ocupado = value;
			}
		}
		protected int? _cantidad_Ocupado = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Cantidad_Restante
		{
			get { return _cantidad_Restante; }
			set
			{
				_cantidad_Restante = value;
			}
		}
		protected int? _cantidad_Restante = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Cantidad_Turnos
		{
			get { return _cantidad_Turnos; }
			set
			{
				_cantidad_Turnos = value;
			}
		}
		protected int? _cantidad_Turnos = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Dia_Secuencia
		{
			get { return _dia_Secuencia; }
			set
			{
				_dia_Secuencia = value;
			}
		}
		protected int? _dia_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual DateTime? Horario_Fecha_Desde
		{
			get { return _horario_Fecha_Desde; }
			set
			{
				_horario_Fecha_Desde = value;
			}
		}
		protected DateTime? _horario_Fecha_Desde = System.DateTime.MinValue;

		/// <summary>
		/// 
		/// </summary>
		public virtual DateTime? Horario_Fecha_Hasta
		{
			get { return _horario_Fecha_Hasta; }
			set
			{
				_horario_Fecha_Hasta = value;
			}
		}
		protected DateTime? _horario_Fecha_Hasta = System.DateTime.MinValue;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Horario_Secuencia
		{
			get { return _horario_Secuencia; }
			set
			{
				_horario_Secuencia = value;
			}
		}
		protected int? _horario_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Horario_Turno_Secuencia
		{
			get { return _horario_Turno_Secuencia; }
			set
			{
				_horario_Turno_Secuencia = value;
			}
		}
		protected int? _horario_Turno_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Ruta_Descripcion
		{
			get { return _ruta_Descripcion; }
			set
			{
				_ruta_Descripcion = value;
			}
		}
		protected string _ruta_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Ruta_Secuencia
		{
			get { return _ruta_Secuencia; }
			set
			{
				_ruta_Secuencia = value;
			}
		}
		protected int? _ruta_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Turno_Cantidad_Publicadores
		{
			get { return _turno_Cantidad_Publicadores; }
			set
			{
				_turno_Cantidad_Publicadores = value;
			}
		}
		protected int? _turno_Cantidad_Publicadores = -1;

		#endregion

        private int _totalRowCount = 0;
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int TotalRowCount
        {
            get
            {
                return this._totalRowCount;
            }
            set
            {
                this._totalRowCount = value;
            }
        }
        

public static OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel LoadOne(int? usuarioNumero)
        {
            var _loadOne = OSIS.PEPPAM.BOM.Proc_Turnos_Disponibles.LoadOne(
usuarioNumero);
            if ((_loadOne == null))
            {
                return new OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel();
            }


	        var _procTurnosDisponibles = new OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel()
            {
                Cantidad_Dias = _loadOne.Cantidad_Dias,
                Cantidad_Ocupado = _loadOne.Cantidad_Ocupado,
                Cantidad_Restante = _loadOne.Cantidad_Restante,
                Cantidad_Turnos = _loadOne.Cantidad_Turnos,
                Dia_Secuencia = _loadOne.Dia_Secuencia,
                Horario_Fecha_Desde = _loadOne.Horario_Fecha_Desde,
                Horario_Fecha_Hasta = _loadOne.Horario_Fecha_Hasta,
                Horario_Secuencia = _loadOne.Horario_Secuencia,
                Horario_Turno_Secuencia = _loadOne.Horario_Turno_Secuencia,
                Ruta_Descripcion = _loadOne.Ruta_Descripcion,
                Ruta_Secuencia = _loadOne.Ruta_Secuencia,
                Turno_Cantidad_Publicadores = _loadOne.Turno_Cantidad_Publicadores
            };
            return _procTurnosDisponibles;
            }


public static List<OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel> Load(int? usuarioNumero)
        {
            var _load = OSIS.PEPPAM.BOM.Proc_Turnos_Disponibles.Load(
usuarioNumero);



            if ((_load == null))
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel>();
            }

            var result = _load.Select(
                x =>
                    new OSIS.PEPPAM.Mvc.Models.Proc_Turnos_DisponiblesModel()
                    {
                Cantidad_Dias = x.Cantidad_Dias.Value,
                Cantidad_Ocupado = x.Cantidad_Ocupado.Value,
                Cantidad_Restante = x.Cantidad_Restante.Value,
                Cantidad_Turnos = x.Cantidad_Turnos.Value,
                Dia_Secuencia = x.Dia_Secuencia.Value,
                Horario_Fecha_Desde = x.Horario_Fecha_Desde.Value,
                Horario_Fecha_Hasta = x.Horario_Fecha_Hasta.Value,
                Horario_Secuencia = x.Horario_Secuencia.Value,
                Horario_Turno_Secuencia = x.Horario_Turno_Secuencia.Value,
                Ruta_Descripcion = x.Ruta_Descripcion,
                Ruta_Secuencia = x.Ruta_Secuencia.Value,
                Turno_Cantidad_Publicadores = x.Turno_Cantidad_Publicadores.Value                    }).ToList();

            return result;
        }

    }
}

