//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

 using System;
  using System.Collections.Generic;
  using System.Linq;
 using System.Runtime.Serialization;
 using CodeFluent.Runtime;
 using CodeFluent.Runtime.Utilities;
namespace OSIS.PEPPAM.Mvc.Models
{
    
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    public partial class Proc_Roles_Funcionalidad_AccionesBase
    {


        
        public Proc_Roles_Funcionalidad_AccionesBase()
        {
        }

		#region Primitive Properties

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Codigo
		{
			get { return _funcionalidad_Accion_Codigo; }
			set
			{
				_funcionalidad_Accion_Codigo = value;
			}
		}
		protected string _funcionalidad_Accion_Codigo = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Css
		{
			get { return _funcionalidad_Accion_Css; }
			set
			{
				_funcionalidad_Accion_Css = value;
			}
		}
		protected string _funcionalidad_Accion_Css = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Descripcion
		{
			get { return _funcionalidad_Accion_Descripcion; }
			set
			{
				_funcionalidad_Accion_Descripcion = value;
			}
		}
		protected string _funcionalidad_Accion_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Explicacion
		{
			get { return _funcionalidad_Accion_Explicacion; }
			set
			{
				_funcionalidad_Accion_Explicacion = value;
			}
		}
		protected string _funcionalidad_Accion_Explicacion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Icono_Large
		{
			get { return _funcionalidad_Accion_Icono_Large; }
			set
			{
				_funcionalidad_Accion_Icono_Large = value;
			}
		}
		protected string _funcionalidad_Accion_Icono_Large = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Icono_Small
		{
			get { return _funcionalidad_Accion_Icono_Small; }
			set
			{
				_funcionalidad_Accion_Icono_Small = value;
			}
		}
		protected string _funcionalidad_Accion_Icono_Small = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Menu
		{
			get { return _funcionalidad_Accion_Menu; }
			set
			{
				_funcionalidad_Accion_Menu = value;
			}
		}
		protected string _funcionalidad_Accion_Menu = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Funcionalidad_Accion_Numero
		{
			get { return _funcionalidad_Accion_Numero; }
			set
			{
				_funcionalidad_Accion_Numero = value;
			}
		}
		protected int? _funcionalidad_Accion_Numero = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Permiso_Descripcion
		{
			get { return _funcionalidad_Accion_Permiso_Descripcion; }
			set
			{
				_funcionalidad_Accion_Permiso_Descripcion = value;
			}
		}
		protected string _funcionalidad_Accion_Permiso_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Permiso_Necesita
		{
			get { return _funcionalidad_Accion_Permiso_Necesita; }
			set
			{
				_funcionalidad_Accion_Permiso_Necesita = value;
			}
		}
		protected string _funcionalidad_Accion_Permiso_Necesita = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Funcionalidad_Accion_Tipo_Secuencia
		{
			get { return _funcionalidad_Accion_Tipo_Secuencia; }
			set
			{
				_funcionalidad_Accion_Tipo_Secuencia = value;
			}
		}
		protected int? _funcionalidad_Accion_Tipo_Secuencia = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Accion_Toolbar
		{
			get { return _funcionalidad_Accion_Toolbar; }
			set
			{
				_funcionalidad_Accion_Toolbar = value;
			}
		}
		protected string _funcionalidad_Accion_Toolbar = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Codigo
		{
			get { return _funcionalidad_Codigo; }
			set
			{
				_funcionalidad_Codigo = value;
			}
		}
		protected string _funcionalidad_Codigo = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Descripcion
		{
			get { return _funcionalidad_Descripcion; }
			set
			{
				_funcionalidad_Descripcion = value;
			}
		}
		protected string _funcionalidad_Descripcion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Explicacion
		{
			get { return _funcionalidad_Explicacion; }
			set
			{
				_funcionalidad_Explicacion = value;
			}
		}
		protected string _funcionalidad_Explicacion = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Nombre
		{
			get { return _funcionalidad_Nombre; }
			set
			{
				_funcionalidad_Nombre = value;
			}
		}
		protected string _funcionalidad_Nombre = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Funcionalidad_Numero
		{
			get { return _funcionalidad_Numero; }
			set
			{
				_funcionalidad_Numero = value;
			}
		}
		protected int? _funcionalidad_Numero = -1;

		/// <summary>
		/// 
		/// </summary>
		public virtual string Funcionalidad_Url
		{
			get { return _funcionalidad_Url; }
			set
			{
				_funcionalidad_Url = value;
			}
		}
		protected string _funcionalidad_Url = string.Empty;

		/// <summary>
		/// 
		/// </summary>
		public virtual int? Modulo_Numero
		{
			get { return _modulo_Numero; }
			set
			{
				_modulo_Numero = value;
			}
		}
		protected int? _modulo_Numero = -1;

		#endregion

        private int _totalRowCount = 0;
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int TotalRowCount
        {
            get
            {
                return this._totalRowCount;
            }
            set
            {
                this._totalRowCount = value;
            }
        }
        

public static OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel LoadOne(int? funcionalidadAccionNumero,int? funcionalidadNumero,int? roleNumero)
        {
            var _loadOne = OSIS.PEPPAM.BOM.Proc_Roles_Funcionalidad_Acciones.LoadOne(
funcionalidadAccionNumero,funcionalidadNumero,roleNumero);
            if ((_loadOne == null))
            {
                return new OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel();
            }


	        var _procRolesFuncionalidadAcciones = new OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel()
            {
                Funcionalidad_Accion_Codigo = _loadOne.Funcionalidad_Accion_Codigo,
                Funcionalidad_Accion_Css = _loadOne.Funcionalidad_Accion_Css,
                Funcionalidad_Accion_Descripcion = _loadOne.Funcionalidad_Accion_Descripcion,
                Funcionalidad_Accion_Explicacion = _loadOne.Funcionalidad_Accion_Explicacion,
                Funcionalidad_Accion_Icono_Large = _loadOne.Funcionalidad_Accion_Icono_Large,
                Funcionalidad_Accion_Icono_Small = _loadOne.Funcionalidad_Accion_Icono_Small,
                Funcionalidad_Accion_Menu = _loadOne.Funcionalidad_Accion_Menu,
                Funcionalidad_Accion_Numero = _loadOne.Funcionalidad_Accion_Numero,
                Funcionalidad_Accion_Permiso_Descripcion = _loadOne.Funcionalidad_Accion_Permiso_Descripcion,
                Funcionalidad_Accion_Permiso_Necesita = _loadOne.Funcionalidad_Accion_Permiso_Necesita,
                Funcionalidad_Accion_Tipo_Secuencia = _loadOne.Funcionalidad_Accion_Tipo_Secuencia,
                Funcionalidad_Accion_Toolbar = _loadOne.Funcionalidad_Accion_Toolbar,
                Funcionalidad_Codigo = _loadOne.Funcionalidad_Codigo,
                Funcionalidad_Descripcion = _loadOne.Funcionalidad_Descripcion,
                Funcionalidad_Explicacion = _loadOne.Funcionalidad_Explicacion,
                Funcionalidad_Nombre = _loadOne.Funcionalidad_Nombre,
                Funcionalidad_Numero = _loadOne.Funcionalidad_Numero,
                Funcionalidad_Url = _loadOne.Funcionalidad_Url,
                Modulo_Numero = _loadOne.Modulo_Numero
            };
            return _procRolesFuncionalidadAcciones;
            }


public static List<OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel> Load(int? funcionalidadAccionNumero,int? funcionalidadNumero,int? roleNumero)
        {
            var _load = OSIS.PEPPAM.BOM.Proc_Roles_Funcionalidad_Acciones.Load(
funcionalidadAccionNumero,funcionalidadNumero,roleNumero);



            if ((_load == null))
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel>();
            }

            var result = _load.Select(
                x =>
                    new OSIS.PEPPAM.Mvc.Models.Proc_Roles_Funcionalidad_AccionesModel()
                    {
                Funcionalidad_Accion_Codigo = x.Funcionalidad_Accion_Codigo,
                Funcionalidad_Accion_Css = x.Funcionalidad_Accion_Css,
                Funcionalidad_Accion_Descripcion = x.Funcionalidad_Accion_Descripcion,
                Funcionalidad_Accion_Explicacion = x.Funcionalidad_Accion_Explicacion,
                Funcionalidad_Accion_Icono_Large = x.Funcionalidad_Accion_Icono_Large,
                Funcionalidad_Accion_Icono_Small = x.Funcionalidad_Accion_Icono_Small,
                Funcionalidad_Accion_Menu = x.Funcionalidad_Accion_Menu,
                Funcionalidad_Accion_Numero = x.Funcionalidad_Accion_Numero.Value,
                Funcionalidad_Accion_Permiso_Descripcion = x.Funcionalidad_Accion_Permiso_Descripcion,
                Funcionalidad_Accion_Permiso_Necesita = x.Funcionalidad_Accion_Permiso_Necesita,
                Funcionalidad_Accion_Tipo_Secuencia = x.Funcionalidad_Accion_Tipo_Secuencia.Value,
                Funcionalidad_Accion_Toolbar = x.Funcionalidad_Accion_Toolbar,
                Funcionalidad_Codigo = x.Funcionalidad_Codigo,
                Funcionalidad_Descripcion = x.Funcionalidad_Descripcion,
                Funcionalidad_Explicacion = x.Funcionalidad_Explicacion,
                Funcionalidad_Nombre = x.Funcionalidad_Nombre,
                Funcionalidad_Numero = x.Funcionalidad_Numero.Value,
                Funcionalidad_Url = x.Funcionalidad_Url,
                Modulo_Numero = x.Modulo_Numero.Value                    }).ToList();

            return result;
        }

    }
}

