//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 5/11/2014 11:32:28 AM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FluentValidation;
using FluentValidation.Attributes;
using FluentValidation.Validators;
using OSIS.PEPPAM.Mvc.Models;

namespace OSIS.PEPPAM.Mvc.Models
{
    [Validator(typeof(Roles_CataValidator))]
    public partial class Roles_CataModel
    {
        // Add your custom members here 

        public List<Roles_Modulos> Modulos { get; set; }

    }

    public partial class Roles_Modulos
    {
        public int Modulo_Numero { get; set; }

        public String Modulo_Nombre { get; set; }

        public String Modulo_Descripcion { get; set; }

        public String Modulo_Explicacion { get; set; }

        public String Modulo_Url { get; set; }

        public String Modulo_Icon { get; set; }

        public String Modulo_Permiso_Descripcion { get; set; }

        public virtual List<OSIS.PEPPAM.Mvc.Models.Sistemas_Funcionalidades_MasterModel> Funcionalidades_ModuloList { get; set; }
        
    }







    public partial class Roles_CataValidator
    {

        public Roles_CataValidator()
        {

            Validators();

        }

        // Add your custom members here 
    }
}


