//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : f.peguero
//    Dominio : SSRL
//    Pc      : DTI_GTE_GIS
//    Fecha   : 02/05/2014 05:30:45 p.m.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Collections.Generic; 
using System.ComponentModel.DataAnnotations; 
using FluentValidation;
using FluentValidation.Attributes;
using FluentValidation.Validators;
using OSIS.PEPPAM.Mvc.Models; 

namespace OSIS.PEPPAM.Mvc.Models 
{ 
[Validator(typeof(Sistemas_Funcionalidades_MasterValidator))]
	public partial class Sistemas_Funcionalidades_MasterModel 
	{ 
		// Add your custom members here 
        public object Tags { get; set; }      // Object of html tags to be applied to checkbox, e.g.: 'new { tagName = "tagValue" }'
        public bool IsSelected { get; set; }  // Boolean value to select a checkbox on the list
	} 
	public partial class Sistemas_Funcionalidades_MasterValidator 
	{ 

 public Sistemas_Funcionalidades_MasterValidator()
{

   Validators();

}

		// Add your custom members here 
	} 
} 


