//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Web; 
using System.Linq; 
using System.Collections.Generic; 
using CodeFluent.Runtime; 
using CodeFluent.Runtime.Utilities; 
using System.ComponentModel.DataAnnotations; 
using FluentValidation; 
using FluentValidation.Attributes; 
using OSIS.PEPPAM.Mvc.Models; 

namespace OSIS.PEPPAM.Mvc.Models 
{ 
	public partial class Sistemas_Descripciones_TransModel
	{

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Codigo")]
		public String Objeto_Codigo { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Codigo")]
		public String Objeto_Sub_Codigo { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Descripcion")]
		public String Objeto_Sub_Descripcion { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Explicacion")]
		public String Objeto_Sub_Explicacion { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Datagrid_Orden")]
		public int Objeto_Sub_Datagrid_Orden { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Datagrid_Mostrar")]
		public String Objeto_Sub_Datagrid_Mostrar { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Editar_Orden")]
		public int Objeto_Sub_Editar_Orden { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Editar_Mostrar")]
		public String Objeto_Sub_Editar_Mostrar { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Detalle_Orden")]
		public int Objeto_Sub_Detalle_Orden { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Objeto_Sub_Detalle_Mostrar")]
		public String Objeto_Sub_Detalle_Mostrar { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Registro_Estado")]
		public String Registro_Estado { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Registro_Fecha")]
		public DateTime Registro_Fecha { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Descripciones_Trans","Registro_Usuario")]
		public String Registro_Usuario { get; set; } 

		#region Navigation Properties

		#endregion

        public virtual string EntityKey
        {
            get
            {
                object[] keys = new object[] {
                        this.Objeto_Codigo,
                        this.Objeto_Sub_Codigo
                 };
                string v = CodeFluentPersistence.BuildEntityKey(keys);
                return v;
            }
            set
            {
                System.Type[] types = new System.Type[] {
                        typeof(string),
                        typeof(string)
                        };
                object[] defaultValues = new object[] {
                        string.Empty,
                        string.Empty
                        };
                object[] v1 = CodeFluentPersistence.ParseEntityKey(value, types, defaultValues);
                this. Objeto_Codigo = ((string)(v1[0]));
                this. Objeto_Sub_Codigo = ((string)(v1[1]));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Objeto_Codigo.ToString();
            }
        }
        

        public Sistemas_Descripciones_TransModel()
        {
            this.Objeto_Codigo = string.Empty;
            this.Objeto_Sub_Codigo = string.Empty;
            this.Objeto_Sub_Descripcion = string.Empty;
            this.Objeto_Sub_Explicacion = string.Empty;
            this.Objeto_Sub_Datagrid_Orden = -1;
            this.Objeto_Sub_Datagrid_Mostrar = string.Empty;
            this.Objeto_Sub_Editar_Orden = -1;
            this.Objeto_Sub_Editar_Mostrar = string.Empty;
            this.Objeto_Sub_Detalle_Orden = -1;
            this.Objeto_Sub_Detalle_Mostrar = string.Empty;
            this.Registro_Estado = "A";
            this.Registro_Fecha = DateTime.Now;
            this.Registro_Usuario = HttpContext.Current != null ? HttpContext.Current.User.Identity.Name : "";
            Sistemas_Descripciones_TransPartial();
        }

            partial void Sistemas_Descripciones_TransPartial();

        public virtual bool Equals(OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans)
        {
            if ((sistemasDescripcionesTrans == null))
            {
                return false;
            }

            if (
                    (this.Objeto_Codigo == string.Empty)
                    ||
                    (this.Objeto_Sub_Codigo == string.Empty)
            )
            {
                return base.Equals(sistemasDescripcionesTrans);
            }

 return ((
                    (this.Objeto_Codigo.Equals(sistemasDescripcionesTrans.Objeto_Codigo))
                    &&
                    (this.Objeto_Sub_Codigo.Equals(sistemasDescripcionesTrans.Objeto_Sub_Codigo))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans = null;
			 sistemasDescripcionesTrans = obj as OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel;
            return this.Equals( sistemasDescripcionesTrans);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        public virtual int CompareTo(OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans)
        {
            if ((sistemasDescripcionesTrans == null))
            {
                throw new System.ArgumentNullException("sistemasDescripcionesTrans");
            }
            int localCompareTo = this.Objeto_Codigo.CompareTo(sistemasDescripcionesTrans.Objeto_Codigo);
            return localCompareTo;
        }

        public static OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel Load(string objeto_Codigo,string objeto_Sub_Codigo)
        {
            var _sistemasDescripcionesTransDb = OSIS.PEPPAM.BOM.Sistemas_Descripciones_Trans.Load(objeto_Codigo,objeto_Sub_Codigo);
	        if (_sistemasDescripcionesTransDb == null)
	        {
                return null;
	        }

	        var _sistemasDescripcionesTrans = new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
            {
                Objeto_Codigo = _sistemasDescripcionesTransDb.Objeto_Codigo,
                Objeto_Sub_Codigo = _sistemasDescripcionesTransDb.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = _sistemasDescripcionesTransDb.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = _sistemasDescripcionesTransDb.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTransDb.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTransDb.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = _sistemasDescripcionesTransDb.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTransDb.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTransDb.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTransDb.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = _sistemasDescripcionesTransDb.Registro_Estado,
                Registro_Fecha = _sistemasDescripcionesTransDb.Registro_Fecha,
                Registro_Usuario = _sistemasDescripcionesTransDb.Registro_Usuario,

            };

	        return _sistemasDescripcionesTrans;
       }

     public virtual bool Save()
	        {
             var _sistemasDescripcionesTransDb = new OSIS.PEPPAM.BOM.Sistemas_Descripciones_Trans()
	            {
                Objeto_Codigo = this.Objeto_Codigo,
                Objeto_Sub_Codigo = this.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = this.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = this.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = this.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = this.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = this.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = this.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = this.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = this.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            var result  = _sistemasDescripcionesTransDb.Save();
             //TODO: Puede ser que solo sean los Identity y no todo los primary keys
             this.Objeto_Codigo = _sistemasDescripcionesTransDb.Objeto_Codigo;
             //TODO: Puede ser que solo sean los Identity y no todo los primary keys
             this.Objeto_Sub_Codigo = _sistemasDescripcionesTransDb.Objeto_Sub_Codigo;

             return result;

	        }

        public static bool Save(OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans)
        {
            if ((sistemasDescripcionesTrans == null))
            {
                return false;
            }
            bool ret = sistemasDescripcionesTrans.Save();
            return ret;
        }

        public static bool Insert(OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans)
        {
            bool ret = OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel.Save(sistemasDescripcionesTrans);
            return ret;
        }

        public static void SaveAll(List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> sistemasDescripcionesTrans)
        {
            int index;
            for (index = (sistemasDescripcionesTrans.Count - 1); (index >= 0); index = (index - 1))
            {
                OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel _sistemasDescripcionesTrans = sistemasDescripcionesTrans[index];
                _sistemasDescripcionesTrans.Save();
            }
        }

        public static bool Delete(OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans)
        {
            if ((sistemasDescripcionesTrans == null))
            {
                return false;
            }
            bool ret = sistemasDescripcionesTrans.Delete();
            return ret;
        }

         public virtual bool Delete()
	        {
             var _sistemasDescripcionesTransDb = new OSIS.PEPPAM.BOM.Sistemas_Descripciones_Trans()
	            {
                Objeto_Codigo = this.Objeto_Codigo,
                Objeto_Sub_Codigo = this.Objeto_Sub_Codigo,

	            };

	            return _sistemasDescripcionesTransDb.Delete();

	        }

        public static bool Delete(string objeto_Codigo,string objeto_Sub_Codigo)
        {
            if ((objeto_Codigo == default(string)))
            {
                return false;
            }
            if ((objeto_Sub_Codigo == default(string)))
            {
                return false;
            }
             var _sistemasDescripcionesTransDb = OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel.Load(objeto_Codigo,objeto_Sub_Codigo);
            return _sistemasDescripcionesTransDb.Delete();
        }

        public string Trace()
	        {
             var _sistemasDescripcionesTransDb = new OSIS.PEPPAM.BOM.Sistemas_Descripciones_Trans()
	            {
                Objeto_Codigo = this.Objeto_Codigo,
                Objeto_Sub_Codigo = this.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = this.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = this.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = this.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = this.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = this.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = this.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = this.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = this.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            return _sistemasDescripcionesTransDb.Trace();

	        }

        public static OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel sistemasDescripcionesTrans;
            System.Type[] types = new System.Type[] {
                    typeof(string),                    typeof(string)                    };
            object[] defaultValues = new object[] {
                    string.Empty,                    string.Empty                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    string var0;            var0 = ((string)(v[0]));
                    string var1;            var1 = ((string)(v[1]));
            sistemasDescripcionesTrans = OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel.Load( var0, var1);
            return sistemasDescripcionesTrans;
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
        public  OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel Clone(bool deep)
        {
             OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel  sistemasDescripcionesTrans = new  OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel();
            this.CopyTo(sistemasDescripcionesTrans , deep);
            return sistemasDescripcionesTrans ;
        }

        public OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel Clone()
        {
            OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel localClone = this.Clone(true);
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Objeto_Codigo") == true))
            {
                this.Objeto_Codigo = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Codigo"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Codigo") == true))
            {
                this.Objeto_Sub_Codigo = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Codigo"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Datagrid_Mostrar") == true))
            {
                this.Objeto_Sub_Datagrid_Mostrar = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Datagrid_Mostrar"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Datagrid_Orden") == true))
            {
                this.Objeto_Sub_Datagrid_Orden = ((int)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Datagrid_Orden"], typeof(int), -1)));
            }
            if ((dict.Contains("Objeto_Sub_Descripcion") == true))
            {
                this.Objeto_Sub_Descripcion = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Descripcion"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Detalle_Mostrar") == true))
            {
                this.Objeto_Sub_Detalle_Mostrar = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Detalle_Mostrar"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Detalle_Orden") == true))
            {
                this.Objeto_Sub_Detalle_Orden = ((int)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Detalle_Orden"], typeof(int), -1)));
            }
            if ((dict.Contains("Objeto_Sub_Editar_Mostrar") == true))
            {
                this.Objeto_Sub_Editar_Mostrar = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Editar_Mostrar"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Objeto_Sub_Editar_Orden") == true))
            {
                this.Objeto_Sub_Editar_Orden = ((int)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Editar_Orden"], typeof(int), -1)));
            }
            if ((dict.Contains("Objeto_Sub_Explicacion") == true))
            {
                this.Objeto_Sub_Explicacion = ((string)(ConvertUtilities.ChangeType(dict["Objeto_Sub_Explicacion"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
        }

        public virtual void CopyTo( OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel  sistemasDescripcionesTrans, bool deep)
        {
            if ((sistemasDescripcionesTrans == null))
            {
                throw new System.ArgumentNullException("sistemasDescripcionesTrans");
            }
            sistemasDescripcionesTrans.Objeto_Codigo = this.Objeto_Codigo;
            sistemasDescripcionesTrans.Objeto_Sub_Codigo = this.Objeto_Sub_Codigo;
            sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar = this.Objeto_Sub_Datagrid_Mostrar;
            sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden = this.Objeto_Sub_Datagrid_Orden;
            sistemasDescripcionesTrans.Objeto_Sub_Descripcion = this.Objeto_Sub_Descripcion;
            sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar = this.Objeto_Sub_Detalle_Mostrar;
            sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden = this.Objeto_Sub_Detalle_Orden;
            sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar = this.Objeto_Sub_Editar_Mostrar;
            sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden = this.Objeto_Sub_Editar_Orden;
            sistemasDescripcionesTrans.Objeto_Sub_Explicacion = this.Objeto_Sub_Explicacion;
            sistemasDescripcionesTrans.Registro_Estado = this.Registro_Estado;
            sistemasDescripcionesTrans.Registro_Fecha = this.Registro_Fecha;
            sistemasDescripcionesTrans.Registro_Usuario = this.Registro_Usuario;
        }

	public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> PageLoadAll(int pageIndex, int pageSize,
	        CodeFluent.Runtime.PageOptions pageOptions)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageLoadAll(pageIndex, pageSize, pageOptions);

	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _sistemasDescripcionesTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
	        {
                Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> LoadAll()
        {
            OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageLoadAll(int.MinValue, int.MaxValue, null);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
            }

            var result = ret.Select(
                _sistemasDescripcionesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
                    {
                Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> PageObjectocodigo(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions ,string objectoCodigo)
        {
            OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageObjectocodigo(int.MinValue, int.MaxValue,pageOptions
,objectoCodigo);
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
            }

            var result = ret.Select(
                _sistemasDescripcionesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
                    {
                        Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                        Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                        Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                        Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                        Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                        Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                        Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                        Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                        Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                        Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                        Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                        Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                        Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> Objectocodigo(string objectoCodigo)
        {
            OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.Objectocodigo(
objectoCodigo);
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
            }

            var result = ret.Select(
                _sistemasDescripcionesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
                    {
                        Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                        Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                        Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                        Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                        Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                        Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                        Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                        Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                        Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                        Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                        Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                        Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                        Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> PageObjectocodigo(int pageIndex, int pageSize ,string objectoCodigo)
        {
            OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageObjectocodigo(int.MinValue, int.MaxValue
,objectoCodigo);
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
            }

            var result = ret.Select(
                _sistemasDescripcionesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
                    {
                        Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                        Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                        Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                        Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                        Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                        Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                        Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                        Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                        Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                        Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                        Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                        Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                        Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,
                    }).ToList();

            return result;
        }


	public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> PageLoadAllPaging(int pageIndex, int pageSize, string searchString,
	        CodeFluent.Runtime.PageOptions pageOptions, out int totalCount)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageLoadAllPaging(pageIndex, pageSize, searchString, pageOptions);

	        totalCount = pageLoadAll.TotalRowCount;
	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _sistemasDescripcionesTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
	        {
                Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel> LoadAllPaging(string searchString, out int totalCount)
        {
            OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Descripciones_TransCollection.PageLoadAllPaging(1, 1000000,searchString, null);

	            totalCount = ret.TotalRowCount;
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel>();
            }

            var result = ret.Select(
                _sistemasDescripcionesTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Descripciones_TransModel()
                    {
                Objeto_Codigo = _sistemasDescripcionesTrans.Objeto_Codigo,
                Objeto_Sub_Codigo = _sistemasDescripcionesTrans.Objeto_Sub_Codigo,
                Objeto_Sub_Descripcion = _sistemasDescripcionesTrans.Objeto_Sub_Descripcion,
                Objeto_Sub_Explicacion = _sistemasDescripcionesTrans.Objeto_Sub_Explicacion,
                Objeto_Sub_Datagrid_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Orden,
                Objeto_Sub_Datagrid_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Datagrid_Mostrar,
                Objeto_Sub_Editar_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Orden,
                Objeto_Sub_Editar_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Editar_Mostrar,
                Objeto_Sub_Detalle_Orden = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Orden,
                Objeto_Sub_Detalle_Mostrar = _sistemasDescripcionesTrans.Objeto_Sub_Detalle_Mostrar,
                Registro_Estado = _sistemasDescripcionesTrans.Registro_Estado,
                Registro_Fecha = _sistemasDescripcionesTrans.Registro_Fecha,
                Registro_Usuario = _sistemasDescripcionesTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

	} 
} 


