//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : f.peguero
//    Dominio : SSRL
//    Pc      : DTI_GTE_GIS
//    Fecha   : 18/06/2014 01:23:35 p.m.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Collections.Generic; 
using System.ComponentModel.DataAnnotations; 
using FluentValidation;
using FluentValidation.Attributes;
using FluentValidation.Validators;
using OSIS.PEPPAM.Mvc.Models; 

namespace OSIS.PEPPAM.Mvc.Models 
{ 
[Validator(typeof(Sistema_Correos_Enviado_TransValidator))]
	public partial class Sistema_Correos_Enviado_TransModel 
	{ 
		// Add your custom members here 

    public Sistema_Correos_Enviado_TransModel(string ss)
    {
        this.Correo_Enviado_Secuencia = -1;
        this.Correos_Secuencia = -1;
        this.Correo_Enviado_Texto = string.Empty;
        this.Correo_Enviado_Fecha = System.DateTime.MinValue;
        this.Registro_Estado = "A";
        this.Registro_Fecha = DateTime.Now;
        
    }
	} 
	public partial class Sistema_Correos_Enviado_TransValidator 
	{ 

 public Sistema_Correos_Enviado_TransValidator()
{

   Validators();

}

		// Add your custom members here 
	} 
} 


