//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Creador : Administrator
//    Dominio : OSISPC
//    Pc      : OSISPC
//    Fecha   : 6/19/2014 1:29:30 PM
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System; 
using System.Web; 
using System.Linq; 
using System.Collections.Generic; 
using CodeFluent.Runtime; 
using CodeFluent.Runtime.Utilities; 
using System.ComponentModel.DataAnnotations; 
using FluentValidation; 
using FluentValidation.Attributes; 
using OSIS.PEPPAM.Mvc.Models; 

namespace OSIS.PEPPAM.Mvc.Models 
{ 
	public partial class Sistemas_Mensaje_TransModel
	{

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Mensaje_Trans","Mensaje_Codigo")]
		public String Mensaje_Codigo { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Mensaje_Trans","Mensaje_Descripcion")]
		public String Mensaje_Descripcion { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Mensaje_Trans","Registro_Estado")]
		public String Registro_Estado { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Mensaje_Trans","Registro_Fecha")]
		public DateTime Registro_Fecha { get; set; } 

		[OSIS.PEPPAM.Mvc.Infrastructure.Mvc.DisplayName("Sistemas_Mensaje_Trans","Registro_Usuario")]
		public String Registro_Usuario { get; set; } 

		#region Navigation Properties

		#endregion

        public virtual string EntityKey
        {
            get
            {
                return this.Mensaje_Codigo;
            }
            set
            {
               this.Mensaje_Codigo = ((string)(ConvertUtilities.ChangeType(value, typeof(string), string.Empty)));
            }
        }

        public virtual string EntityDisplayName
        {
            get
            {
                return this.Mensaje_Codigo.ToString();
            }
        }
        

        public Sistemas_Mensaje_TransModel()
        {
            this.Mensaje_Codigo = string.Empty;
            this.Mensaje_Descripcion = string.Empty;
            this.Registro_Estado = "A";
            this.Registro_Fecha = DateTime.Now;
            this.Registro_Usuario = HttpContext.Current != null ? HttpContext.Current.User.Identity.Name : "";
            Sistemas_Mensaje_TransPartial();
        }

            partial void Sistemas_Mensaje_TransPartial();

        public virtual bool Equals(OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans)
        {
            if ((sistemasMensajeTrans == null))
            {
                return false;
            }

            if (
                    (this.Mensaje_Codigo == string.Empty)
            )
            {
                return base.Equals(sistemasMensajeTrans);
            }

 return ((
                    (this.Mensaje_Codigo.Equals(sistemasMensajeTrans.Mensaje_Codigo))
                        )== true);
        }

        public override bool Equals(object obj)
        {
            OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans = null;
			 sistemasMensajeTrans = obj as OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel;
            return this.Equals( sistemasMensajeTrans);
        }

        public override int GetHashCode()
        {
            if ((this.EntityKey == null))
            {
                return base.GetHashCode();
            }
            return this.EntityKey.GetHashCode();
        }
        
        public virtual int CompareTo(OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans)
        {
            if ((sistemasMensajeTrans == null))
            {
                throw new System.ArgumentNullException("sistemasMensajeTrans");
            }
            int localCompareTo = this.Mensaje_Codigo.CompareTo(sistemasMensajeTrans.Mensaje_Codigo);
            return localCompareTo;
        }

        public static OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel Load(string mensaje_Codigo)
        {
            var _sistemasMensajeTransDb = OSIS.PEPPAM.BOM.Sistemas_Mensaje_Trans.Load(mensaje_Codigo);
	        if (_sistemasMensajeTransDb == null)
	        {
                return null;
	        }

	        var _sistemasMensajeTrans = new OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel()
            {
                Mensaje_Codigo = _sistemasMensajeTransDb.Mensaje_Codigo,
                Mensaje_Descripcion = _sistemasMensajeTransDb.Mensaje_Descripcion,
                Registro_Estado = _sistemasMensajeTransDb.Registro_Estado,
                Registro_Fecha = _sistemasMensajeTransDb.Registro_Fecha,
                Registro_Usuario = _sistemasMensajeTransDb.Registro_Usuario,

            };

	        return _sistemasMensajeTrans;
       }

     public virtual bool Save()
	        {
             var _sistemasMensajeTransDb = new OSIS.PEPPAM.BOM.Sistemas_Mensaje_Trans()
	            {
                Mensaje_Codigo = this.Mensaje_Codigo,
                Mensaje_Descripcion = this.Mensaje_Descripcion,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            var result  = _sistemasMensajeTransDb.Save();
             //TODO: Puede ser que solo sean los Identity y no todo los primary keys
             this.Mensaje_Codigo = _sistemasMensajeTransDb.Mensaje_Codigo;

             return result;

	        }

        public static bool Save(OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans)
        {
            if ((sistemasMensajeTrans == null))
            {
                return false;
            }
            bool ret = sistemasMensajeTrans.Save();
            return ret;
        }

        public static bool Insert(OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans)
        {
            bool ret = OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel.Save(sistemasMensajeTrans);
            return ret;
        }

        public static void SaveAll(List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel> sistemasMensajeTrans)
        {
            int index;
            for (index = (sistemasMensajeTrans.Count - 1); (index >= 0); index = (index - 1))
            {
                OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel _sistemasMensajeTrans = sistemasMensajeTrans[index];
                _sistemasMensajeTrans.Save();
            }
        }

        public static bool Delete(OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans)
        {
            if ((sistemasMensajeTrans == null))
            {
                return false;
            }
            bool ret = sistemasMensajeTrans.Delete();
            return ret;
        }

         public virtual bool Delete()
	        {
             var _sistemasMensajeTransDb = new OSIS.PEPPAM.BOM.Sistemas_Mensaje_Trans()
	            {
                Mensaje_Codigo = this.Mensaje_Codigo,

	            };

	            return _sistemasMensajeTransDb.Delete();

	        }

        public static bool Delete(string mensaje_Codigo)
        {
            if ((mensaje_Codigo == default(string)))
            {
                return false;
            }
             var _sistemasMensajeTransDb = OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel.Load(mensaje_Codigo);
            return _sistemasMensajeTransDb.Delete();
        }

        public string Trace()
	        {
             var _sistemasMensajeTransDb = new OSIS.PEPPAM.BOM.Sistemas_Mensaje_Trans()
	            {
                Mensaje_Codigo = this.Mensaje_Codigo,
                Mensaje_Descripcion = this.Mensaje_Descripcion,
                Registro_Estado = this.Registro_Estado,
                Registro_Fecha = this.Registro_Fecha,
                Registro_Usuario = this.Registro_Usuario
	            };

	            return _sistemasMensajeTransDb.Trace();

	        }

        public static OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel LoadByEntityKey(string key)
        {
            if ((key == string.Empty))
            {
                return null;
            }
            OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel sistemasMensajeTrans;
            System.Type[] types = new System.Type[] {
                    typeof(string)                    };
            object[] defaultValues = new object[] {
                    string.Empty                    };
            object[] v = CodeFluentPersistence.ParseEntityKey(key, types, defaultValues);
                    string var0;            var0 = ((string)(v[0]));
            sistemasMensajeTrans = OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel.Load( var0);
            return sistemasMensajeTrans;
        }


// Metodos Definidos en el Modelo y las propiedades CollectionKey
        public  OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel Clone(bool deep)
        {
             OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel  sistemasMensajeTrans = new  OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel();
            this.CopyTo(sistemasMensajeTrans , deep);
            return sistemasMensajeTrans ;
        }

        public OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel Clone()
        {
            OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel localClone = this.Clone(true);
            return localClone;
        }

        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Mensaje_Codigo") == true))
            {
                this.Mensaje_Codigo = ((string)(ConvertUtilities.ChangeType(dict["Mensaje_Codigo"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Mensaje_Descripcion") == true))
            {
                this.Mensaje_Descripcion = ((string)(ConvertUtilities.ChangeType(dict["Mensaje_Descripcion"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Estado") == true))
            {
                this.Registro_Estado = ((string)(ConvertUtilities.ChangeType(dict["Registro_Estado"], typeof(string), string.Empty)));
            }
            if ((dict.Contains("Registro_Fecha") == true))
            {
                this.Registro_Fecha = ((DateTime)(ConvertUtilities.ChangeType(dict["Registro_Fecha"], typeof(DateTime), System.DateTime.MinValue)));
            }
            if ((dict.Contains("Registro_Usuario") == true))
            {
                this.Registro_Usuario = ((string)(ConvertUtilities.ChangeType(dict["Registro_Usuario"], typeof(string), string.Empty)));
            }
        }

        public virtual void CopyTo( OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel  sistemasMensajeTrans, bool deep)
        {
            if ((sistemasMensajeTrans == null))
            {
                throw new System.ArgumentNullException("sistemasMensajeTrans");
            }
            sistemasMensajeTrans.Mensaje_Codigo = this.Mensaje_Codigo;
            sistemasMensajeTrans.Mensaje_Descripcion = this.Mensaje_Descripcion;
            sistemasMensajeTrans.Registro_Estado = this.Registro_Estado;
            sistemasMensajeTrans.Registro_Fecha = this.Registro_Fecha;
            sistemasMensajeTrans.Registro_Usuario = this.Registro_Usuario;
        }

	public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel> PageLoadAll(int pageIndex, int pageSize,
	        CodeFluent.Runtime.PageOptions pageOptions)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection.PageLoadAll(pageIndex, pageSize, pageOptions);

	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _sistemasMensajeTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel()
	        {
                Mensaje_Codigo = _sistemasMensajeTrans.Mensaje_Codigo,
                Mensaje_Descripcion = _sistemasMensajeTrans.Mensaje_Descripcion,
                Registro_Estado = _sistemasMensajeTrans.Registro_Estado,
                Registro_Fecha = _sistemasMensajeTrans.Registro_Fecha,
                Registro_Usuario = _sistemasMensajeTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel> LoadAll()
        {
            OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection.PageLoadAll(int.MinValue, int.MaxValue, null);

            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel>();
            }

            var result = ret.Select(
                _sistemasMensajeTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel()
                    {
                Mensaje_Codigo = _sistemasMensajeTrans.Mensaje_Codigo,
                Mensaje_Descripcion = _sistemasMensajeTrans.Mensaje_Descripcion,
                Registro_Estado = _sistemasMensajeTrans.Registro_Estado,
                Registro_Fecha = _sistemasMensajeTrans.Registro_Fecha,
                Registro_Usuario = _sistemasMensajeTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

	public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel> PageLoadAllPaging(int pageIndex, int pageSize, string searchString,
	        CodeFluent.Runtime.PageOptions pageOptions, out int totalCount)
	    {
	        var pageLoadAll = OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection.PageLoadAllPaging(pageIndex, pageSize, searchString, pageOptions);

	        totalCount = pageLoadAll.TotalRowCount;
	        if (pageLoadAll == null)
	        {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel>();
	        }

	        var result =  pageLoadAll.Select(
                _sistemasMensajeTrans => 
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel()
	        {
                Mensaje_Codigo = _sistemasMensajeTrans.Mensaje_Codigo,
                Mensaje_Descripcion = _sistemasMensajeTrans.Mensaje_Descripcion,
                Registro_Estado = _sistemasMensajeTrans.Registro_Estado,
                Registro_Fecha = _sistemasMensajeTrans.Registro_Fecha,
                Registro_Usuario = _sistemasMensajeTrans.Registro_Usuario,

	        }).ToList();

	        return result;
	    }

        public static List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel> LoadAllPaging(string searchString, out int totalCount)
        {
            OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection ret = OSIS.PEPPAM.BOM.Sistemas_Mensaje_TransCollection.PageLoadAllPaging(1, 1000000,searchString, null);

	            totalCount = ret.TotalRowCount;
            if (ret == null)
            {
                return new List<OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel>();
            }

            var result = ret.Select(
                _sistemasMensajeTrans =>
                    new OSIS.PEPPAM.Mvc.Models.Sistemas_Mensaje_TransModel()
                    {
                Mensaje_Codigo = _sistemasMensajeTrans.Mensaje_Codigo,
                Mensaje_Descripcion = _sistemasMensajeTrans.Mensaje_Descripcion,
                Registro_Estado = _sistemasMensajeTrans.Registro_Estado,
                Registro_Fecha = _sistemasMensajeTrans.Registro_Fecha,
                Registro_Usuario = _sistemasMensajeTrans.Registro_Usuario,

                    }).ToList();

            return result;
        }

	} 
} 


